// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type EnumPlatform string

const (
	EnumPlatformTelegram   EnumPlatform = "telegram"
	EnumPlatformRocketchat EnumPlatform = "rocketchat"
)

func (e *EnumPlatform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumPlatform(s)
	case string:
		*e = EnumPlatform(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumPlatform: %T", src)
	}
	return nil
}

type NullEnumPlatform struct {
	EnumPlatform EnumPlatform `json:"enum_platform"`
	Valid        bool         `json:"valid"` // Valid is true if EnumPlatform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumPlatform) Scan(value interface{}) error {
	if value == nil {
		ns.EnumPlatform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumPlatform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumPlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumPlatform), nil
}

type EnumStudentStatus string

const (
	EnumStudentStatusACTIVE            EnumStudentStatus = "ACTIVE"
	EnumStudentStatusTEMPORARYBLOCKING EnumStudentStatus = "TEMPORARY_BLOCKING"
	EnumStudentStatusEXPELLED          EnumStudentStatus = "EXPELLED"
	EnumStudentStatusBLOCKED           EnumStudentStatus = "BLOCKED"
	EnumStudentStatusFROZEN            EnumStudentStatus = "FROZEN"
	EnumStudentStatusSTUDYCOMPLETED    EnumStudentStatus = "STUDY_COMPLETED"
)

func (e *EnumStudentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumStudentStatus(s)
	case string:
		*e = EnumStudentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumStudentStatus: %T", src)
	}
	return nil
}

type NullEnumStudentStatus struct {
	EnumStudentStatus EnumStudentStatus `json:"enum_student_status"`
	Valid             bool              `json:"valid"` // Valid is true if EnumStudentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumStudentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EnumStudentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumStudentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumStudentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumStudentStatus), nil
}

type EnumUserRole string

const (
	EnumUserRoleUser      EnumUserRole = "user"
	EnumUserRoleAdmin     EnumUserRole = "admin"
	EnumUserRoleModerator EnumUserRole = "moderator"
	EnumUserRoleOwner     EnumUserRole = "owner"
)

func (e *EnumUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumUserRole(s)
	case string:
		*e = EnumUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumUserRole: %T", src)
	}
	return nil
}

type NullEnumUserRole struct {
	EnumUserRole EnumUserRole `json:"enum_user_role"`
	Valid        bool         `json:"valid"` // Valid is true if EnumUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.EnumUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumUserRole), nil
}

type ApiKey struct {
	ID            int64              `json:"id"`
	UserAccountID int64              `json:"user_account_id"`
	KeyHash       string             `json:"key_hash"`
	Prefix        string             `json:"prefix"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

type AuthVerificationCode struct {
	ID        int64              `json:"id"`
	StudentID pgtype.Text        `json:"student_id"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Campuse struct {
	ID        pgtype.UUID        `json:"id"`
	ShortName string             `json:"short_name"`
	FullName  string             `json:"full_name"`
	Timezone  pgtype.Text        `json:"timezone"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Club struct {
	ID           int16              `json:"id"`
	CampusID     pgtype.UUID        `json:"campus_id"`
	LeaderLogin  pgtype.Text        `json:"leader_login"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	CategoryID   int16              `json:"category_id"`
	ExternalLink pgtype.Text        `json:"external_link"`
	IsLocal      pgtype.Bool        `json:"is_local"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ClubCategory struct {
	ID        int16              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Coalition struct {
	ID        int16              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type FsmUserState struct {
	UserID       int64              `json:"user_id"`
	CurrentFlow  string             `json:"current_flow"`
	CurrentState string             `json:"current_state"`
	Context      []byte             `json:"context"`
	Language     string             `json:"language"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PlatformCredential struct {
	StudentID        string             `json:"student_id"`
	PasswordEnc      []byte             `json:"password_enc"`
	PasswordNonce    []byte             `json:"password_nonce"`
	AccessToken      pgtype.Text        `json:"access_token"`
	AccessExpiresAt  pgtype.Timestamptz `json:"access_expires_at"`
	RefreshTokenEnc  []byte             `json:"refresh_token_enc"`
	RefreshNonce     []byte             `json:"refresh_nonce"`
	RefreshExpiresAt pgtype.Timestamptz `json:"refresh_expires_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RocketchatCredential struct {
	StudentID  string             `json:"student_id"`
	RcTokenEnc []byte             `json:"rc_token_enc"`
	RcNonce    []byte             `json:"rc_nonce"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Skill struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Category  pgtype.Text        `json:"category"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Student struct {
	S21Login           string                `json:"s21_login"`
	RocketchatID       string                `json:"rocketchat_id"`
	CampusID           pgtype.UUID           `json:"campus_id"`
	CoalitionID        pgtype.Int2           `json:"coalition_id"`
	Status             NullEnumStudentStatus `json:"status"`
	ParallelName       pgtype.Text           `json:"parallel_name"`
	Level              pgtype.Int4           `json:"level"`
	ExpValue           pgtype.Int4           `json:"exp_value"`
	Prp                pgtype.Int4           `json:"prp"`
	Crp                pgtype.Int4           `json:"crp"`
	Coins              pgtype.Int4           `json:"coins"`
	Timezone           string                `json:"timezone"`
	AlternativeContact pgtype.Text           `json:"alternative_contact"`
	HasCoffeeBan       pgtype.Bool           `json:"has_coffee_ban"`
	CreatedAt          pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz    `json:"updated_at"`
	ClassName          pgtype.Text           `json:"class_name"`
}

type StudentSkill struct {
	StudentID string             `json:"student_id"`
	SkillID   int32              `json:"skill_id"`
	Value     int32              `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserAccount struct {
	ID           int64              `json:"id"`
	StudentID    string             `json:"student_id"`
	Platform     EnumPlatform       `json:"platform"`
	ExternalID   string             `json:"external_id"`
	Username     pgtype.Text        `json:"username"`
	IsSearchable pgtype.Bool        `json:"is_searchable"`
	Role         NullEnumUserRole   `json:"role"`
	LinkedAt     pgtype.Timestamptz `json:"linked_at"`
}

type UserBotSetting struct {
	ID                   int64              `json:"id"`
	UserAccountID        int64              `json:"user_account_id"`
	LanguageCode         pgtype.Text        `json:"language_code"`
	NotificationsEnabled pgtype.Bool        `json:"notifications_enabled"`
	ReviewPostCampusIds  []byte             `json:"review_post_campus_ids"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
