// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type EnumPlatform string

const (
	EnumPlatformTelegram   EnumPlatform = "telegram"
	EnumPlatformRocketchat EnumPlatform = "rocketchat"
)

func (e *EnumPlatform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumPlatform(s)
	case string:
		*e = EnumPlatform(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumPlatform: %T", src)
	}
	return nil
}

type NullEnumPlatform struct {
	EnumPlatform EnumPlatform `json:"enum_platform"`
	Valid        bool         `json:"valid"` // Valid is true if EnumPlatform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumPlatform) Scan(value interface{}) error {
	if value == nil {
		ns.EnumPlatform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumPlatform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumPlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumPlatform), nil
}

type EnumReviewStatus string

const (
	EnumReviewStatusSEARCHING   EnumReviewStatus = "SEARCHING"
	EnumReviewStatusNEGOTIATING EnumReviewStatus = "NEGOTIATING"
	EnumReviewStatusPAUSED      EnumReviewStatus = "PAUSED"
	EnumReviewStatusCLOSED      EnumReviewStatus = "CLOSED"
)

func (e *EnumReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumReviewStatus(s)
	case string:
		*e = EnumReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumReviewStatus: %T", src)
	}
	return nil
}

type NullEnumReviewStatus struct {
	EnumReviewStatus EnumReviewStatus `json:"enum_review_status"`
	Valid            bool             `json:"valid"` // Valid is true if EnumReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EnumReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumReviewStatus), nil
}

type EnumStudentStatus string

const (
	EnumStudentStatusACTIVE            EnumStudentStatus = "ACTIVE"
	EnumStudentStatusTEMPORARYBLOCKING EnumStudentStatus = "TEMPORARY_BLOCKING"
	EnumStudentStatusEXPELLED          EnumStudentStatus = "EXPELLED"
	EnumStudentStatusBLOCKED           EnumStudentStatus = "BLOCKED"
	EnumStudentStatusFROZEN            EnumStudentStatus = "FROZEN"
	EnumStudentStatusSTUDYCOMPLETED    EnumStudentStatus = "STUDY_COMPLETED"
)

func (e *EnumStudentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumStudentStatus(s)
	case string:
		*e = EnumStudentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumStudentStatus: %T", src)
	}
	return nil
}

type NullEnumStudentStatus struct {
	EnumStudentStatus EnumStudentStatus `json:"enum_student_status"`
	Valid             bool              `json:"valid"` // Valid is true if EnumStudentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumStudentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EnumStudentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumStudentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumStudentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumStudentStatus), nil
}

type EnumUserRole string

const (
	EnumUserRoleUser      EnumUserRole = "user"
	EnumUserRoleAdmin     EnumUserRole = "admin"
	EnumUserRoleModerator EnumUserRole = "moderator"
	EnumUserRoleOwner     EnumUserRole = "owner"
)

func (e *EnumUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumUserRole(s)
	case string:
		*e = EnumUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumUserRole: %T", src)
	}
	return nil
}

type NullEnumUserRole struct {
	EnumUserRole EnumUserRole `json:"enum_user_role"`
	Valid        bool         `json:"valid"` // Valid is true if EnumUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.EnumUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumUserRole), nil
}

type ApiKey struct {
	ID            int64              `json:"id"`
	UserAccountID int64              `json:"user_account_id"`
	KeyHash       string             `json:"key_hash"`
	Prefix        string             `json:"prefix"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

type AuthVerificationCode struct {
	ID        int64              `json:"id"`
	S21Login  pgtype.Text        `json:"s21_login"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Book struct {
	ID          int16              `json:"id"`
	CampusID    pgtype.UUID        `json:"campus_id"`
	Title       string             `json:"title"`
	Author      string             `json:"author"`
	Category    string             `json:"category"`
	TotalStock  int32              `json:"total_stock"`
	Description pgtype.Text        `json:"description"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type BookLoan struct {
	ID         int64              `json:"id"`
	CampusID   pgtype.UUID        `json:"campus_id"`
	BookID     int16              `json:"book_id"`
	UserID     int64              `json:"user_id"`
	BorrowedAt pgtype.Timestamptz `json:"borrowed_at"`
	DueAt      pgtype.Timestamptz `json:"due_at"`
	ReturnedAt pgtype.Timestamptz `json:"returned_at"`
}

type Campuse struct {
	ID             pgtype.UUID        `json:"id"`
	ShortName      string             `json:"short_name"`
	FullName       string             `json:"full_name"`
	Timezone       pgtype.Text        `json:"timezone"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	LeaderName     pgtype.Text        `json:"leader_name"`
	LeaderFormLink pgtype.Text        `json:"leader_form_link"`
}

type Club struct {
	ID           int16              `json:"id"`
	CampusID     pgtype.UUID        `json:"campus_id"`
	LeaderLogin  pgtype.Text        `json:"leader_login"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	CategoryID   int16              `json:"category_id"`
	ExternalLink pgtype.Text        `json:"external_link"`
	IsLocal      pgtype.Bool        `json:"is_local"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ClubCategory struct {
	ID        int16              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Coalition struct {
	ID        int16              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Course struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	Code        pgtype.Text        `json:"code"`
	SyncBatchID int64              `json:"sync_batch_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type FsmUserState struct {
	UserID       int64              `json:"user_id"`
	CurrentFlow  string             `json:"current_flow"`
	CurrentState string             `json:"current_state"`
	Context      []byte             `json:"context"`
	Language     string             `json:"language"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Node struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	ParentID    pgtype.Int8        `json:"parent_id"`
	SyncBatchID int64              `json:"sync_batch_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ParticipantSkill struct {
	S21Login  string             `json:"s21_login"`
	SkillID   int32              `json:"skill_id"`
	Value     int32              `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ParticipantStatsCache struct {
	S21Login     string             `json:"s21_login"`
	CampusID     pgtype.UUID        `json:"campus_id"`
	CoalitionID  pgtype.Int2        `json:"coalition_id"`
	Status       EnumStudentStatus  `json:"status"`
	Level        int32              `json:"level"`
	ExpValue     int32              `json:"exp_value"`
	Prp          int32              `json:"prp"`
	Crp          int32              `json:"crp"`
	Coins        int32              `json:"coins"`
	ParallelName pgtype.Text        `json:"parallel_name"`
	ClassName    pgtype.Text        `json:"class_name"`
	Integrity    pgtype.Float4      `json:"integrity"`
	Friendliness pgtype.Float4      `json:"friendliness"`
	Punctuality  pgtype.Float4      `json:"punctuality"`
	Thoroughness pgtype.Float4      `json:"thoroughness"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LatSyncedAt  pgtype.Timestamptz `json:"lat_synced_at"`
}

type PlatformCredential struct {
	S21Login         string             `json:"s21_login"`
	PasswordEnc      []byte             `json:"password_enc"`
	PasswordNonce    []byte             `json:"password_nonce"`
	AccessToken      pgtype.Text        `json:"access_token"`
	AccessExpiresAt  pgtype.Timestamptz `json:"access_expires_at"`
	RefreshTokenEnc  []byte             `json:"refresh_token_enc"`
	RefreshNonce     []byte             `json:"refresh_nonce"`
	RefreshExpiresAt pgtype.Timestamptz `json:"refresh_expires_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID          int64              `json:"id"`
	CourseID    pgtype.Int8        `json:"course_id"`
	Title       string             `json:"title"`
	Code        pgtype.Text        `json:"code"`
	SyncBatchID int64              `json:"sync_batch_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProjectNode struct {
	ProjectID   int64              `json:"project_id"`
	NodeID      int64              `json:"node_id"`
	SyncBatchID int64              `json:"sync_batch_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ProjectSearch struct {
	ProjectID   int64              `json:"project_id"`
	SearchText  string             `json:"search_text"`
	Document    interface{}        `json:"document"`
	SyncBatchID int64              `json:"sync_batch_id"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RegisteredUser struct {
	S21Login           string             `json:"s21_login"`
	RocketchatID       string             `json:"rocketchat_id"`
	Timezone           string             `json:"timezone"`
	AlternativeContact pgtype.Text        `json:"alternative_contact"`
	HasCoffeeBan       pgtype.Bool        `json:"has_coffee_ban"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ReviewRequest struct {
	ID                                    int64              `json:"id"`
	RequesterUserID                       int64              `json:"requester_user_id"`
	RequesterS21Login                     string             `json:"requester_s21_login"`
	RequesterCampusID                     pgtype.UUID        `json:"requester_campus_id"`
	ProjectID                             int64              `json:"project_id"`
	ProjectName                           string             `json:"project_name"`
	ProjectType                           string             `json:"project_type"`
	AvailabilityText                      string             `json:"availability_text"`
	RequesterTimezone                     string             `json:"requester_timezone"`
	RequesterTimezoneOffset               string             `json:"requester_timezone_offset"`
	Status                                EnumReviewStatus   `json:"status"`
	ViewCount                             int32              `json:"view_count"`
	ResponseCount                         int32              `json:"response_count"`
	CreatedAt                             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                             pgtype.Timestamptz `json:"updated_at"`
	ClosedAt                              pgtype.Timestamptz `json:"closed_at"`
	NegotiatingReviewerUserID             pgtype.Int8        `json:"negotiating_reviewer_user_id"`
	NegotiatingReviewerS21Login           pgtype.Text        `json:"negotiating_reviewer_s21_login"`
	NegotiatingReviewerTelegramUsername   pgtype.Text        `json:"negotiating_reviewer_telegram_username"`
	NegotiatingReviewerRocketchatID       pgtype.Text        `json:"negotiating_reviewer_rocketchat_id"`
	NegotiatingReviewerAlternativeContact pgtype.Text        `json:"negotiating_reviewer_alternative_contact"`
	NegotiatingStartedAt                  pgtype.Timestamptz `json:"negotiating_started_at"`
}

type RocketchatCredential struct {
	S21Login   string             `json:"s21_login"`
	RcTokenEnc []byte             `json:"rc_token_enc"`
	RcNonce    []byte             `json:"rc_nonce"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Room struct {
	ID          int16              `json:"id"`
	CampusID    pgtype.UUID        `json:"campus_id"`
	Name        string             `json:"name"`
	MinDuration int32              `json:"min_duration"`
	MaxDuration int32              `json:"max_duration"`
	IsActive    pgtype.Bool        `json:"is_active"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Capacity    int32              `json:"capacity"`
}

type RoomBooking struct {
	ID              int64              `json:"id"`
	CampusID        pgtype.UUID        `json:"campus_id"`
	RoomID          int16              `json:"room_id"`
	UserID          int64              `json:"user_id"`
	BookingDate     pgtype.Date        `json:"booking_date"`
	StartTime       pgtype.Time        `json:"start_time"`
	DurationMinutes int32              `json:"duration_minutes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Skill struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Category  pgtype.Text        `json:"category"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserAccount struct {
	ID           int64              `json:"id"`
	S21Login     string             `json:"s21_login"`
	Platform     EnumPlatform       `json:"platform"`
	ExternalID   string             `json:"external_id"`
	Username     pgtype.Text        `json:"username"`
	IsSearchable pgtype.Bool        `json:"is_searchable"`
	Role         NullEnumUserRole   `json:"role"`
	LinkedAt     pgtype.Timestamptz `json:"linked_at"`
}

type UserBotSetting struct {
	ID                   int64              `json:"id"`
	UserAccountID        int64              `json:"user_account_id"`
	LanguageCode         pgtype.Text        `json:"language_code"`
	NotificationsEnabled pgtype.Bool        `json:"notifications_enabled"`
	ReviewPostCampusIds  []byte             `json:"review_post_campus_ids"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
