// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (
    user_account_id, key_hash, prefix, expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_account_id, key_hash, prefix, created_at, revoked_at, expires_at
`

type CreateApiKeyParams struct {
	UserAccountID int64              `json:"user_account_id"`
	KeyHash       string             `json:"key_hash"`
	Prefix        string             `json:"prefix"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.UserAccountID,
		arg.KeyHash,
		arg.Prefix,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.KeyHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createAuthVerificationCode = `-- name: CreateAuthVerificationCode :one
INSERT INTO auth_verification_codes (
    student_id, code, expires_at
) VALUES (
    $1, $2, $3
)
RETURNING id, student_id, code, expires_at, created_at
`

type CreateAuthVerificationCodeParams struct {
	StudentID pgtype.Text        `json:"student_id"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthVerificationCode(ctx context.Context, arg CreateAuthVerificationCodeParams) (AuthVerificationCode, error) {
	row := q.db.QueryRow(ctx, createAuthVerificationCode, arg.StudentID, arg.Code, arg.ExpiresAt)
	var i AuthVerificationCode
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserAccount = `-- name: CreateUserAccount :one
INSERT INTO user_accounts (
    student_id, platform, external_id, username, is_searchable, role
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, student_id, platform, external_id, username, is_searchable, role, linked_at
`

type CreateUserAccountParams struct {
	StudentID    string           `json:"student_id"`
	Platform     EnumPlatform     `json:"platform"`
	ExternalID   string           `json:"external_id"`
	Username     pgtype.Text      `json:"username"`
	IsSearchable pgtype.Bool      `json:"is_searchable"`
	Role         NullEnumUserRole `json:"role"`
}

func (q *Queries) CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createUserAccount,
		arg.StudentID,
		arg.Platform,
		arg.ExternalID,
		arg.Username,
		arg.IsSearchable,
		arg.Role,
	)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Platform,
		&i.ExternalID,
		&i.Username,
		&i.IsSearchable,
		&i.Role,
		&i.LinkedAt,
	)
	return i, err
}

const deactivateClubsByCampus = `-- name: DeactivateClubsByCampus :exec
UPDATE clubs
SET is_active = false, updated_at = CURRENT_TIMESTAMP
WHERE campus_id = $1
`

func (q *Queries) DeactivateClubsByCampus(ctx context.Context, campusID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateClubsByCampus, campusID)
	return err
}

const deleteAllAuthVerificationCodes = `-- name: DeleteAllAuthVerificationCodes :exec
DELETE FROM auth_verification_codes
WHERE student_id = $1
`

func (q *Queries) DeleteAllAuthVerificationCodes(ctx context.Context, studentID pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteAllAuthVerificationCodes, studentID)
	return err
}

const deleteAuthVerificationCode = `-- name: DeleteAuthVerificationCode :exec
DELETE FROM auth_verification_codes
WHERE student_id = $1 AND code = $2
`

type DeleteAuthVerificationCodeParams struct {
	StudentID pgtype.Text `json:"student_id"`
	Code      string      `json:"code"`
}

func (q *Queries) DeleteAuthVerificationCode(ctx context.Context, arg DeleteAuthVerificationCodeParams) error {
	_, err := q.db.Exec(ctx, deleteAuthVerificationCode, arg.StudentID, arg.Code)
	return err
}

const deleteExpiredAuthVerificationCodes = `-- name: DeleteExpiredAuthVerificationCodes :exec
DELETE FROM auth_verification_codes
WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredAuthVerificationCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthVerificationCodes)
	return err
}

const getActiveApiKey = `-- name: GetActiveApiKey :one
SELECT id, user_account_id, key_hash, prefix, created_at, revoked_at, expires_at FROM api_keys
WHERE user_account_id = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP)
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveApiKey(ctx context.Context, userAccountID int64) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getActiveApiKey, userAccountID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.KeyHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, user_account_id, key_hash, prefix, created_at, revoked_at, expires_at FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP)
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.KeyHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getCampusByShortName = `-- name: GetCampusByShortName :one
SELECT id, short_name, full_name, timezone, is_active, created_at, updated_at FROM campuses WHERE short_name = $1
`

func (q *Queries) GetCampusByShortName(ctx context.Context, shortName string) (Campuse, error) {
	row := q.db.QueryRow(ctx, getCampusByShortName, shortName)
	var i Campuse
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.FullName,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFSMState = `-- name: GetFSMState :one
SELECT user_id, current_flow, current_state, context, language, updated_at FROM fsm_user_states WHERE user_id = $1
`

func (q *Queries) GetFSMState(ctx context.Context, userID int64) (FsmUserState, error) {
	row := q.db.QueryRow(ctx, getFSMState, userID)
	var i FsmUserState
	err := row.Scan(
		&i.UserID,
		&i.CurrentFlow,
		&i.CurrentState,
		&i.Context,
		&i.Language,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastAuthVerificationCode = `-- name: GetLastAuthVerificationCode :one
SELECT id, student_id, code, expires_at, created_at FROM auth_verification_codes
WHERE student_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastAuthVerificationCode(ctx context.Context, studentID pgtype.Text) (AuthVerificationCode, error) {
	row := q.db.QueryRow(ctx, getLastAuthVerificationCode, studentID)
	var i AuthVerificationCode
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformCredentials = `-- name: GetPlatformCredentials :one
SELECT student_id, password_enc, password_nonce, access_token, access_expires_at, refresh_token_enc, refresh_nonce, refresh_expires_at, updated_at FROM platform_credentials 
WHERE student_id = $1
`

func (q *Queries) GetPlatformCredentials(ctx context.Context, studentID string) (PlatformCredential, error) {
	row := q.db.QueryRow(ctx, getPlatformCredentials, studentID)
	var i PlatformCredential
	err := row.Scan(
		&i.StudentID,
		&i.PasswordEnc,
		&i.PasswordNonce,
		&i.AccessToken,
		&i.AccessExpiresAt,
		&i.RefreshTokenEnc,
		&i.RefreshNonce,
		&i.RefreshExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRocketChatCredentials = `-- name: GetRocketChatCredentials :one
SELECT student_id, rc_token_enc, rc_nonce, updated_at FROM rocketchat_credentials
WHERE student_id = $1
`

func (q *Queries) GetRocketChatCredentials(ctx context.Context, studentID string) (RocketchatCredential, error) {
	row := q.db.QueryRow(ctx, getRocketChatCredentials, studentID)
	var i RocketchatCredential
	err := row.Scan(
		&i.StudentID,
		&i.RcTokenEnc,
		&i.RcNonce,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentByRocketChatId = `-- name: GetStudentByRocketChatId :one
SELECT s21_login, rocketchat_id, campus_id, coalition_id, status, parallel_name, level, exp_value, prp, crp, coins, timezone, alternative_contact, has_coffee_ban, created_at, updated_at FROM students WHERE rocketchat_id = $1
`

func (q *Queries) GetStudentByRocketChatId(ctx context.Context, rocketchatID string) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByRocketChatId, rocketchatID)
	var i Student
	err := row.Scan(
		&i.S21Login,
		&i.RocketchatID,
		&i.CampusID,
		&i.CoalitionID,
		&i.Status,
		&i.ParallelName,
		&i.Level,
		&i.ExpValue,
		&i.Prp,
		&i.Crp,
		&i.Coins,
		&i.Timezone,
		&i.AlternativeContact,
		&i.HasCoffeeBan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentByS21Login = `-- name: GetStudentByS21Login :one

SELECT s21_login, rocketchat_id, campus_id, coalition_id, status, parallel_name, level, exp_value, prp, crp, coins, timezone, alternative_contact, has_coffee_ban, created_at, updated_at FROM students WHERE s21_login = $1
`

// queries.sql
func (q *Queries) GetStudentByS21Login(ctx context.Context, s21Login string) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByS21Login, s21Login)
	var i Student
	err := row.Scan(
		&i.S21Login,
		&i.RocketchatID,
		&i.CampusID,
		&i.CoalitionID,
		&i.Status,
		&i.ParallelName,
		&i.Level,
		&i.ExpValue,
		&i.Prp,
		&i.Crp,
		&i.Coins,
		&i.Timezone,
		&i.AlternativeContact,
		&i.HasCoffeeBan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentProfile = `-- name: GetStudentProfile :one
SELECT s.s21_login, s.rocketchat_id, s.campus_id, s.coalition_id, s.status, s.parallel_name, s.level, s.exp_value, s.prp, s.crp, s.coins, s.timezone, s.alternative_contact, s.has_coffee_ban, s.created_at, s.updated_at, c.short_name as campus_name, cool.name as coalition_name
FROM students s
LEFT JOIN campuses c ON s.campus_id = c.id
LEFT JOIN coalitions cool ON s.coalition_id = cool.id
WHERE s.s21_login = $1
`

type GetStudentProfileRow struct {
	S21Login           string                `json:"s21_login"`
	RocketchatID       string                `json:"rocketchat_id"`
	CampusID           pgtype.UUID           `json:"campus_id"`
	CoalitionID        pgtype.Int2           `json:"coalition_id"`
	Status             NullEnumStudentStatus `json:"status"`
	ParallelName       pgtype.Text           `json:"parallel_name"`
	Level              pgtype.Int4           `json:"level"`
	ExpValue           pgtype.Int4           `json:"exp_value"`
	Prp                pgtype.Int4           `json:"prp"`
	Crp                pgtype.Int4           `json:"crp"`
	Coins              pgtype.Int4           `json:"coins"`
	Timezone           string                `json:"timezone"`
	AlternativeContact pgtype.Text           `json:"alternative_contact"`
	HasCoffeeBan       pgtype.Bool           `json:"has_coffee_ban"`
	CreatedAt          pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz    `json:"updated_at"`
	CampusName         pgtype.Text           `json:"campus_name"`
	CoalitionName      pgtype.Text           `json:"coalition_name"`
}

func (q *Queries) GetStudentProfile(ctx context.Context, s21Login string) (GetStudentProfileRow, error) {
	row := q.db.QueryRow(ctx, getStudentProfile, s21Login)
	var i GetStudentProfileRow
	err := row.Scan(
		&i.S21Login,
		&i.RocketchatID,
		&i.CampusID,
		&i.CoalitionID,
		&i.Status,
		&i.ParallelName,
		&i.Level,
		&i.ExpValue,
		&i.Prp,
		&i.Crp,
		&i.Coins,
		&i.Timezone,
		&i.AlternativeContact,
		&i.HasCoffeeBan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CampusName,
		&i.CoalitionName,
	)
	return i, err
}

const getUserAccountByExternalId = `-- name: GetUserAccountByExternalId :one
SELECT id, student_id, platform, external_id, username, is_searchable, role, linked_at FROM user_accounts 
WHERE platform = $1 AND external_id = $2
`

type GetUserAccountByExternalIdParams struct {
	Platform   EnumPlatform `json:"platform"`
	ExternalID string       `json:"external_id"`
}

func (q *Queries) GetUserAccountByExternalId(ctx context.Context, arg GetUserAccountByExternalIdParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByExternalId, arg.Platform, arg.ExternalID)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Platform,
		&i.ExternalID,
		&i.Username,
		&i.IsSearchable,
		&i.Role,
		&i.LinkedAt,
	)
	return i, err
}

const getUserAccountByStudentId = `-- name: GetUserAccountByStudentId :one
SELECT id, student_id, platform, external_id, username, is_searchable, role, linked_at FROM user_accounts
WHERE student_id = $1
`

func (q *Queries) GetUserAccountByStudentId(ctx context.Context, studentID string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByStudentId, studentID)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Platform,
		&i.ExternalID,
		&i.Username,
		&i.IsSearchable,
		&i.Role,
		&i.LinkedAt,
	)
	return i, err
}

const getUserBotSettings = `-- name: GetUserBotSettings :one
SELECT id, user_account_id, language_code, notifications_enabled, review_post_campus_ids, created_at, updated_at FROM user_bot_settings 
WHERE user_account_id = $1
`

func (q *Queries) GetUserBotSettings(ctx context.Context, userAccountID int64) (UserBotSetting, error) {
	row := q.db.QueryRow(ctx, getUserBotSettings, userAccountID)
	var i UserBotSetting
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.LanguageCode,
		&i.NotificationsEnabled,
		&i.ReviewPostCampusIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidAuthVerificationCode = `-- name: GetValidAuthVerificationCode :one
SELECT id, student_id, code, expires_at, created_at FROM auth_verification_codes
WHERE student_id = $1 AND code = $2 AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC
LIMIT 1
`

type GetValidAuthVerificationCodeParams struct {
	StudentID pgtype.Text `json:"student_id"`
	Code      string      `json:"code"`
}

func (q *Queries) GetValidAuthVerificationCode(ctx context.Context, arg GetValidAuthVerificationCodeParams) (AuthVerificationCode, error) {
	row := q.db.QueryRow(ctx, getValidAuthVerificationCode, arg.StudentID, arg.Code)
	var i AuthVerificationCode
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeOldApiKeys = `-- name: RevokeOldApiKeys :exec
UPDATE api_keys
SET revoked_at = CURRENT_TIMESTAMP
WHERE user_account_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeOldApiKeys(ctx context.Context, userAccountID int64) error {
	_, err := q.db.Exec(ctx, revokeOldApiKeys, userAccountID)
	return err
}

const upsertCampus = `-- name: UpsertCampus :one
INSERT INTO campuses (id, short_name, full_name, timezone, is_active)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    short_name = EXCLUDED.short_name,
    full_name = EXCLUDED.full_name,
    timezone = EXCLUDED.timezone,
    is_active = EXCLUDED.is_active,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, short_name, full_name, timezone, is_active, created_at, updated_at
`

type UpsertCampusParams struct {
	ID        pgtype.UUID `json:"id"`
	ShortName string      `json:"short_name"`
	FullName  string      `json:"full_name"`
	Timezone  pgtype.Text `json:"timezone"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) UpsertCampus(ctx context.Context, arg UpsertCampusParams) (Campuse, error) {
	row := q.db.QueryRow(ctx, upsertCampus,
		arg.ID,
		arg.ShortName,
		arg.FullName,
		arg.Timezone,
		arg.IsActive,
	)
	var i Campuse
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.FullName,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertClub = `-- name: UpsertClub :one
INSERT INTO clubs (
    id, campus_id, leader_login, name, description, category_id,
    external_link, is_local, is_active, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, CURRENT_TIMESTAMP
)
ON CONFLICT (campus_id, id) DO UPDATE SET
    leader_login = EXCLUDED.leader_login,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    category_id = EXCLUDED.category_id,
    external_link = EXCLUDED.external_link,
    is_local = EXCLUDED.is_local,
    is_active = EXCLUDED.is_active,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, campus_id, leader_login, name, description, category_id, external_link, is_local, is_active, created_at, updated_at
`

type UpsertClubParams struct {
	ID           int16       `json:"id"`
	CampusID     pgtype.UUID `json:"campus_id"`
	LeaderLogin  pgtype.Text `json:"leader_login"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	CategoryID   int16       `json:"category_id"`
	ExternalLink pgtype.Text `json:"external_link"`
	IsLocal      pgtype.Bool `json:"is_local"`
	IsActive     pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpsertClub(ctx context.Context, arg UpsertClubParams) (Club, error) {
	row := q.db.QueryRow(ctx, upsertClub,
		arg.ID,
		arg.CampusID,
		arg.LeaderLogin,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.ExternalLink,
		arg.IsLocal,
		arg.IsActive,
	)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.CampusID,
		&i.LeaderLogin,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.ExternalLink,
		&i.IsLocal,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertClubCategory = `-- name: UpsertClubCategory :one
INSERT INTO club_categories (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, created_at
`

func (q *Queries) UpsertClubCategory(ctx context.Context, name string) (ClubCategory, error) {
	row := q.db.QueryRow(ctx, upsertClubCategory, name)
	var i ClubCategory
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const upsertFSMState = `-- name: UpsertFSMState :exec
INSERT INTO fsm_user_states (
    user_id, current_flow, current_state, context, language
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (user_id) DO UPDATE SET
    current_flow = EXCLUDED.current_flow,
    current_state = EXCLUDED.current_state,
    context = EXCLUDED.context,
    language = EXCLUDED.language,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertFSMStateParams struct {
	UserID       int64  `json:"user_id"`
	CurrentFlow  string `json:"current_flow"`
	CurrentState string `json:"current_state"`
	Context      []byte `json:"context"`
	Language     string `json:"language"`
}

func (q *Queries) UpsertFSMState(ctx context.Context, arg UpsertFSMStateParams) error {
	_, err := q.db.Exec(ctx, upsertFSMState,
		arg.UserID,
		arg.CurrentFlow,
		arg.CurrentState,
		arg.Context,
		arg.Language,
	)
	return err
}

const upsertPlatformCredentials = `-- name: UpsertPlatformCredentials :exec
INSERT INTO platform_credentials (
    student_id, password_enc, password_nonce, 
    access_token, access_expires_at, refresh_token_enc, 
    refresh_nonce, refresh_expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (student_id) DO UPDATE SET
    password_enc = EXCLUDED.password_enc,
    password_nonce = EXCLUDED.password_nonce,
    access_token = EXCLUDED.access_token,
    access_expires_at = EXCLUDED.access_expires_at,
    refresh_token_enc = EXCLUDED.refresh_token_enc,
    refresh_nonce = EXCLUDED.refresh_nonce,
    refresh_expires_at = EXCLUDED.refresh_expires_at,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertPlatformCredentialsParams struct {
	StudentID        string             `json:"student_id"`
	PasswordEnc      []byte             `json:"password_enc"`
	PasswordNonce    []byte             `json:"password_nonce"`
	AccessToken      pgtype.Text        `json:"access_token"`
	AccessExpiresAt  pgtype.Timestamptz `json:"access_expires_at"`
	RefreshTokenEnc  []byte             `json:"refresh_token_enc"`
	RefreshNonce     []byte             `json:"refresh_nonce"`
	RefreshExpiresAt pgtype.Timestamptz `json:"refresh_expires_at"`
}

func (q *Queries) UpsertPlatformCredentials(ctx context.Context, arg UpsertPlatformCredentialsParams) error {
	_, err := q.db.Exec(ctx, upsertPlatformCredentials,
		arg.StudentID,
		arg.PasswordEnc,
		arg.PasswordNonce,
		arg.AccessToken,
		arg.AccessExpiresAt,
		arg.RefreshTokenEnc,
		arg.RefreshNonce,
		arg.RefreshExpiresAt,
	)
	return err
}

const upsertRocketChatCredentials = `-- name: UpsertRocketChatCredentials :exec
INSERT INTO rocketchat_credentials (
    student_id, rc_token_enc, rc_nonce
) VALUES (
    $1, $2, $3
)
ON CONFLICT (student_id) DO UPDATE SET
    rc_token_enc = EXCLUDED.rc_token_enc,
    rc_nonce = EXCLUDED.rc_nonce,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertRocketChatCredentialsParams struct {
	StudentID  string `json:"student_id"`
	RcTokenEnc []byte `json:"rc_token_enc"`
	RcNonce    []byte `json:"rc_nonce"`
}

func (q *Queries) UpsertRocketChatCredentials(ctx context.Context, arg UpsertRocketChatCredentialsParams) error {
	_, err := q.db.Exec(ctx, upsertRocketChatCredentials, arg.StudentID, arg.RcTokenEnc, arg.RcNonce)
	return err
}

const upsertStudent = `-- name: UpsertStudent :one
INSERT INTO students (
    s21_login, rocketchat_id, campus_id, coalition_id, status, 
    timezone, alternative_contact, has_coffee_ban
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (s21_login) DO UPDATE SET
    rocketchat_id = EXCLUDED.rocketchat_id,
    campus_id = EXCLUDED.campus_id,
    coalition_id = EXCLUDED.coalition_id,
    status = EXCLUDED.status,
    timezone = EXCLUDED.timezone,
    alternative_contact = EXCLUDED.alternative_contact,
    has_coffee_ban = EXCLUDED.has_coffee_ban,
    updated_at = CURRENT_TIMESTAMP
RETURNING s21_login, rocketchat_id, campus_id, coalition_id, status, parallel_name, level, exp_value, prp, crp, coins, timezone, alternative_contact, has_coffee_ban, created_at, updated_at
`

type UpsertStudentParams struct {
	S21Login           string                `json:"s21_login"`
	RocketchatID       string                `json:"rocketchat_id"`
	CampusID           pgtype.UUID           `json:"campus_id"`
	CoalitionID        pgtype.Int2           `json:"coalition_id"`
	Status             NullEnumStudentStatus `json:"status"`
	Timezone           string                `json:"timezone"`
	AlternativeContact pgtype.Text           `json:"alternative_contact"`
	HasCoffeeBan       pgtype.Bool           `json:"has_coffee_ban"`
}

func (q *Queries) UpsertStudent(ctx context.Context, arg UpsertStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, upsertStudent,
		arg.S21Login,
		arg.RocketchatID,
		arg.CampusID,
		arg.CoalitionID,
		arg.Status,
		arg.Timezone,
		arg.AlternativeContact,
		arg.HasCoffeeBan,
	)
	var i Student
	err := row.Scan(
		&i.S21Login,
		&i.RocketchatID,
		&i.CampusID,
		&i.CoalitionID,
		&i.Status,
		&i.ParallelName,
		&i.Level,
		&i.ExpValue,
		&i.Prp,
		&i.Crp,
		&i.Coins,
		&i.Timezone,
		&i.AlternativeContact,
		&i.HasCoffeeBan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserBotSettings = `-- name: UpsertUserBotSettings :one
INSERT INTO user_bot_settings (
    user_account_id, language_code, notifications_enabled, review_post_campus_ids
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (user_account_id) DO UPDATE SET
    language_code = EXCLUDED.language_code,
    notifications_enabled = EXCLUDED.notifications_enabled,
    review_post_campus_ids = EXCLUDED.review_post_campus_ids,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_account_id, language_code, notifications_enabled, review_post_campus_ids, created_at, updated_at
`

type UpsertUserBotSettingsParams struct {
	UserAccountID        int64       `json:"user_account_id"`
	LanguageCode         pgtype.Text `json:"language_code"`
	NotificationsEnabled pgtype.Bool `json:"notifications_enabled"`
	ReviewPostCampusIds  []byte      `json:"review_post_campus_ids"`
}

func (q *Queries) UpsertUserBotSettings(ctx context.Context, arg UpsertUserBotSettingsParams) (UserBotSetting, error) {
	row := q.db.QueryRow(ctx, upsertUserBotSettings,
		arg.UserAccountID,
		arg.LanguageCode,
		arg.NotificationsEnabled,
		arg.ReviewPostCampusIds,
	)
	var i UserBotSetting
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.LanguageCode,
		&i.NotificationsEnabled,
		&i.ReviewPostCampusIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
