// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelRoomBooking = `-- name: CancelRoomBooking :exec
DELETE FROM room_bookings
WHERE id = $1 AND user_id = $2
`

type CancelRoomBookingParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) CancelRoomBooking(ctx context.Context, arg CancelRoomBookingParams) error {
	_, err := q.db.Exec(ctx, cancelRoomBooking, arg.ID, arg.UserID)
	return err
}

const countBooksByCampus = `-- name: CountBooksByCampus :one
SELECT 
    count(*)::int as total_books,
    (count(*) - (SELECT count(*) FROM book_loans bl WHERE bl.campus_id = $1 AND bl.returned_at IS NULL))::int as available_books
FROM books
WHERE campus_id = $1 AND is_active = true
`

type CountBooksByCampusRow struct {
	TotalBooks     int32 `json:"total_books"`
	AvailableBooks int32 `json:"available_books"`
}

func (q *Queries) CountBooksByCampus(ctx context.Context, campusID pgtype.UUID) (CountBooksByCampusRow, error) {
	row := q.db.QueryRow(ctx, countBooksByCampus, campusID)
	var i CountBooksByCampusRow
	err := row.Scan(&i.TotalBooks, &i.AvailableBooks)
	return i, err
}

const countBooksByCategory = `-- name: CountBooksByCategory :one
SELECT count(*)::int
FROM books
WHERE campus_id = $1 AND is_active = true AND category = $2
`

type CountBooksByCategoryParams struct {
	CampusID pgtype.UUID `json:"campus_id"`
	Category string      `json:"category"`
}

func (q *Queries) CountBooksByCategory(ctx context.Context, arg CountBooksByCategoryParams) (int32, error) {
	row := q.db.QueryRow(ctx, countBooksByCategory, arg.CampusID, arg.Category)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSearchBooks = `-- name: CountSearchBooks :one
SELECT count(*)::int
FROM books
WHERE campus_id = $1 AND is_active = true AND (title ILIKE '%' || $2 || '%' OR author ILIKE '%' || $2 || '%')
`

type CountSearchBooksParams struct {
	CampusID pgtype.UUID `json:"campus_id"`
	Column2  pgtype.Text `json:"column_2"`
}

func (q *Queries) CountSearchBooks(ctx context.Context, arg CountSearchBooksParams) (int32, error) {
	row := q.db.QueryRow(ctx, countSearchBooks, arg.CampusID, arg.Column2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (
    user_account_id, key_hash, prefix, expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_account_id, key_hash, prefix, created_at, revoked_at, expires_at
`

type CreateApiKeyParams struct {
	UserAccountID int64              `json:"user_account_id"`
	KeyHash       string             `json:"key_hash"`
	Prefix        string             `json:"prefix"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.UserAccountID,
		arg.KeyHash,
		arg.Prefix,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.KeyHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createAuthVerificationCode = `-- name: CreateAuthVerificationCode :one
INSERT INTO auth_verification_codes (
    s21_login, code, expires_at
) VALUES (
    $1, $2, $3
)
RETURNING id, s21_login, code, expires_at, created_at
`

type CreateAuthVerificationCodeParams struct {
	S21Login  pgtype.Text        `json:"s21_login"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthVerificationCode(ctx context.Context, arg CreateAuthVerificationCodeParams) (AuthVerificationCode, error) {
	row := q.db.QueryRow(ctx, createAuthVerificationCode, arg.S21Login, arg.Code, arg.ExpiresAt)
	var i AuthVerificationCode
	err := row.Scan(
		&i.ID,
		&i.S21Login,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createBookLoan = `-- name: CreateBookLoan :one
WITH availability AS (
    SELECT (total_stock - (SELECT count(*) FROM book_loans WHERE campus_id = $1 AND book_id = $2 AND returned_at IS NULL)) as available
    FROM books
    WHERE campus_id = $1 AND id = $2
)
INSERT INTO book_loans (
    campus_id, book_id, user_id, due_at
)
SELECT $1, $2, $3, $4
FROM availability
WHERE available > 0
RETURNING id, campus_id, book_id, user_id, borrowed_at, due_at, returned_at
`

type CreateBookLoanParams struct {
	CampusID pgtype.UUID        `json:"campus_id"`
	BookID   int16              `json:"book_id"`
	UserID   int64              `json:"user_id"`
	DueAt    pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) CreateBookLoan(ctx context.Context, arg CreateBookLoanParams) (BookLoan, error) {
	row := q.db.QueryRow(ctx, createBookLoan,
		arg.CampusID,
		arg.BookID,
		arg.UserID,
		arg.DueAt,
	)
	var i BookLoan
	err := row.Scan(
		&i.ID,
		&i.CampusID,
		&i.BookID,
		&i.UserID,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
	)
	return i, err
}

const createRoomBooking = `-- name: CreateRoomBooking :one
INSERT INTO room_bookings (
    campus_id, room_id, user_id, booking_date, start_time, duration_minutes
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (campus_id, room_id, booking_date, start_time) DO NOTHING
RETURNING id, campus_id, room_id, user_id, booking_date, start_time, duration_minutes, created_at
`

type CreateRoomBookingParams struct {
	CampusID        pgtype.UUID `json:"campus_id"`
	RoomID          int16       `json:"room_id"`
	UserID          int64       `json:"user_id"`
	BookingDate     pgtype.Date `json:"booking_date"`
	StartTime       pgtype.Time `json:"start_time"`
	DurationMinutes int32       `json:"duration_minutes"`
}

func (q *Queries) CreateRoomBooking(ctx context.Context, arg CreateRoomBookingParams) (RoomBooking, error) {
	row := q.db.QueryRow(ctx, createRoomBooking,
		arg.CampusID,
		arg.RoomID,
		arg.UserID,
		arg.BookingDate,
		arg.StartTime,
		arg.DurationMinutes,
	)
	var i RoomBooking
	err := row.Scan(
		&i.ID,
		&i.CampusID,
		&i.RoomID,
		&i.UserID,
		&i.BookingDate,
		&i.StartTime,
		&i.DurationMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const createUserAccount = `-- name: CreateUserAccount :one
INSERT INTO user_accounts (
    s21_login, platform, external_id, username, is_searchable, role
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, s21_login, platform, external_id, username, is_searchable, role, linked_at
`

type CreateUserAccountParams struct {
	S21Login     string           `json:"s21_login"`
	Platform     EnumPlatform     `json:"platform"`
	ExternalID   string           `json:"external_id"`
	Username     pgtype.Text      `json:"username"`
	IsSearchable pgtype.Bool      `json:"is_searchable"`
	Role         NullEnumUserRole `json:"role"`
}

func (q *Queries) CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createUserAccount,
		arg.S21Login,
		arg.Platform,
		arg.ExternalID,
		arg.Username,
		arg.IsSearchable,
		arg.Role,
	)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.S21Login,
		&i.Platform,
		&i.ExternalID,
		&i.Username,
		&i.IsSearchable,
		&i.Role,
		&i.LinkedAt,
	)
	return i, err
}

const deactivateBooksByCampus = `-- name: DeactivateBooksByCampus :exec
UPDATE books
SET is_active = false, updated_at = CURRENT_TIMESTAMP
WHERE campus_id = $1
`

func (q *Queries) DeactivateBooksByCampus(ctx context.Context, campusID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateBooksByCampus, campusID)
	return err
}

const deactivateClubsByCampus = `-- name: DeactivateClubsByCampus :exec
UPDATE clubs
SET is_active = false, updated_at = CURRENT_TIMESTAMP
WHERE campus_id = $1
`

func (q *Queries) DeactivateClubsByCampus(ctx context.Context, campusID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateClubsByCampus, campusID)
	return err
}

const deactivateRoomsByCampus = `-- name: DeactivateRoomsByCampus :exec
UPDATE rooms
SET is_active = false, updated_at = CURRENT_TIMESTAMP
WHERE campus_id = $1
`

func (q *Queries) DeactivateRoomsByCampus(ctx context.Context, campusID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateRoomsByCampus, campusID)
	return err
}

const deleteAllAuthVerificationCodes = `-- name: DeleteAllAuthVerificationCodes :exec
DELETE FROM auth_verification_codes
WHERE s21_login = $1
`

func (q *Queries) DeleteAllAuthVerificationCodes(ctx context.Context, s21Login pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteAllAuthVerificationCodes, s21Login)
	return err
}

const deleteAuthVerificationCode = `-- name: DeleteAuthVerificationCode :exec
DELETE FROM auth_verification_codes
WHERE s21_login = $1 AND code = $2
`

type DeleteAuthVerificationCodeParams struct {
	S21Login pgtype.Text `json:"s21_login"`
	Code     string      `json:"code"`
}

func (q *Queries) DeleteAuthVerificationCode(ctx context.Context, arg DeleteAuthVerificationCodeParams) error {
	_, err := q.db.Exec(ctx, deleteAuthVerificationCode, arg.S21Login, arg.Code)
	return err
}

const deleteExpiredAuthVerificationCodes = `-- name: DeleteExpiredAuthVerificationCodes :exec
DELETE FROM auth_verification_codes
WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredAuthVerificationCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthVerificationCodes)
	return err
}

const deleteUserAccountByExternalId = `-- name: DeleteUserAccountByExternalId :exec
DELETE FROM user_accounts
WHERE platform = $1 AND external_id = $2
`

type DeleteUserAccountByExternalIdParams struct {
	Platform   EnumPlatform `json:"platform"`
	ExternalID string       `json:"external_id"`
}

func (q *Queries) DeleteUserAccountByExternalId(ctx context.Context, arg DeleteUserAccountByExternalIdParams) error {
	_, err := q.db.Exec(ctx, deleteUserAccountByExternalId, arg.Platform, arg.ExternalID)
	return err
}

const getActiveApiKey = `-- name: GetActiveApiKey :one
SELECT id, user_account_id, key_hash, prefix, created_at, revoked_at, expires_at FROM api_keys
WHERE user_account_id = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP)
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveApiKey(ctx context.Context, userAccountID int64) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getActiveApiKey, userAccountID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.KeyHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getActiveRoomsByCampus = `-- name: GetActiveRoomsByCampus :many
SELECT id, campus_id, name, min_duration, max_duration, is_active, description, created_at, updated_at, capacity FROM rooms
WHERE campus_id = $1 AND is_active = true
ORDER BY id
`

func (q *Queries) GetActiveRoomsByCampus(ctx context.Context, campusID pgtype.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, getActiveRoomsByCampus, campusID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.CampusID,
			&i.Name,
			&i.MinDuration,
			&i.MaxDuration,
			&i.IsActive,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllActiveCampuses = `-- name: GetAllActiveCampuses :many
SELECT id, short_name, full_name, timezone
FROM campuses
WHERE is_active = true
ORDER BY short_name
`

type GetAllActiveCampusesRow struct {
	ID        pgtype.UUID `json:"id"`
	ShortName string      `json:"short_name"`
	FullName  string      `json:"full_name"`
	Timezone  pgtype.Text `json:"timezone"`
}

func (q *Queries) GetAllActiveCampuses(ctx context.Context) ([]GetAllActiveCampusesRow, error) {
	rows, err := q.db.Query(ctx, getAllActiveCampuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActiveCampusesRow
	for rows.Next() {
		var i GetAllActiveCampusesRow
		if err := rows.Scan(
			&i.ID,
			&i.ShortName,
			&i.FullName,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, user_account_id, key_hash, prefix, created_at, revoked_at, expires_at FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP)
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.KeyHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getBookAuthors = `-- name: GetBookAuthors :many
SELECT DISTINCT author FROM books
WHERE campus_id = $1 AND is_active = true
ORDER BY author
`

func (q *Queries) GetBookAuthors(ctx context.Context, campusID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getBookAuthors, campusID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var author string
		if err := rows.Scan(&author); err != nil {
			return nil, err
		}
		items = append(items, author)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookByID = `-- name: GetBookByID :one
SELECT b.id, b.campus_id, b.title, b.author, b.category, b.total_stock, b.description, b.is_active, b.created_at, b.updated_at, 
       (b.total_stock - (SELECT count(*) FROM book_loans bl WHERE bl.campus_id = b.campus_id AND bl.book_id = b.id AND bl.returned_at IS NULL))::int as available_stock
FROM books b
WHERE b.campus_id = $1 AND b.id = $2
`

type GetBookByIDParams struct {
	CampusID pgtype.UUID `json:"campus_id"`
	ID       int16       `json:"id"`
}

type GetBookByIDRow struct {
	ID             int16              `json:"id"`
	CampusID       pgtype.UUID        `json:"campus_id"`
	Title          string             `json:"title"`
	Author         string             `json:"author"`
	Category       string             `json:"category"`
	TotalStock     int32              `json:"total_stock"`
	Description    pgtype.Text        `json:"description"`
	IsActive       pgtype.Bool        `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AvailableStock int32              `json:"available_stock"`
}

func (q *Queries) GetBookByID(ctx context.Context, arg GetBookByIDParams) (GetBookByIDRow, error) {
	row := q.db.QueryRow(ctx, getBookByID, arg.CampusID, arg.ID)
	var i GetBookByIDRow
	err := row.Scan(
		&i.ID,
		&i.CampusID,
		&i.Title,
		&i.Author,
		&i.Category,
		&i.TotalStock,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableStock,
	)
	return i, err
}

const getBookCategories = `-- name: GetBookCategories :many
SELECT DISTINCT category FROM books
WHERE campus_id = $1 AND is_active = true
ORDER BY category
`

func (q *Queries) GetBookCategories(ctx context.Context, campusID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getBookCategories, campusID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksByCampus = `-- name: GetBooksByCampus :many
SELECT b.id, b.campus_id, b.title, b.author, b.category, b.total_stock, b.description, b.is_active, b.created_at, b.updated_at,
       (b.total_stock - (SELECT count(*) FROM book_loans bl WHERE bl.campus_id = b.campus_id AND bl.book_id = b.id AND bl.returned_at IS NULL))::int as available_stock
FROM books b
WHERE b.campus_id = $1 AND b.is_active = true
ORDER BY b.title
LIMIT $2 OFFSET $3
`

type GetBooksByCampusParams struct {
	CampusID pgtype.UUID `json:"campus_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type GetBooksByCampusRow struct {
	ID             int16              `json:"id"`
	CampusID       pgtype.UUID        `json:"campus_id"`
	Title          string             `json:"title"`
	Author         string             `json:"author"`
	Category       string             `json:"category"`
	TotalStock     int32              `json:"total_stock"`
	Description    pgtype.Text        `json:"description"`
	IsActive       pgtype.Bool        `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AvailableStock int32              `json:"available_stock"`
}

func (q *Queries) GetBooksByCampus(ctx context.Context, arg GetBooksByCampusParams) ([]GetBooksByCampusRow, error) {
	rows, err := q.db.Query(ctx, getBooksByCampus, arg.CampusID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBooksByCampusRow
	for rows.Next() {
		var i GetBooksByCampusRow
		if err := rows.Scan(
			&i.ID,
			&i.CampusID,
			&i.Title,
			&i.Author,
			&i.Category,
			&i.TotalStock,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvailableStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksByCampusAndAuthor = `-- name: GetBooksByCampusAndAuthor :many
SELECT b.id, b.campus_id, b.title, b.author, b.category, b.total_stock, b.description, b.is_active, b.created_at, b.updated_at,
       (b.total_stock - (SELECT count(*) FROM book_loans bl WHERE bl.campus_id = b.campus_id AND bl.book_id = b.id AND bl.returned_at IS NULL))::int as available_stock
FROM books b
WHERE b.campus_id = $1 AND b.is_active = true AND b.author = $2
ORDER BY b.title
LIMIT $3 OFFSET $4
`

type GetBooksByCampusAndAuthorParams struct {
	CampusID pgtype.UUID `json:"campus_id"`
	Author   string      `json:"author"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type GetBooksByCampusAndAuthorRow struct {
	ID             int16              `json:"id"`
	CampusID       pgtype.UUID        `json:"campus_id"`
	Title          string             `json:"title"`
	Author         string             `json:"author"`
	Category       string             `json:"category"`
	TotalStock     int32              `json:"total_stock"`
	Description    pgtype.Text        `json:"description"`
	IsActive       pgtype.Bool        `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AvailableStock int32              `json:"available_stock"`
}

func (q *Queries) GetBooksByCampusAndAuthor(ctx context.Context, arg GetBooksByCampusAndAuthorParams) ([]GetBooksByCampusAndAuthorRow, error) {
	rows, err := q.db.Query(ctx, getBooksByCampusAndAuthor,
		arg.CampusID,
		arg.Author,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBooksByCampusAndAuthorRow
	for rows.Next() {
		var i GetBooksByCampusAndAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.CampusID,
			&i.Title,
			&i.Author,
			&i.Category,
			&i.TotalStock,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvailableStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksByCampusAndCategory = `-- name: GetBooksByCampusAndCategory :many
SELECT b.id, b.campus_id, b.title, b.author, b.category, b.total_stock, b.description, b.is_active, b.created_at, b.updated_at,
       (b.total_stock - (SELECT count(*) FROM book_loans bl WHERE bl.campus_id = b.campus_id AND bl.book_id = b.id AND bl.returned_at IS NULL))::int as available_stock
FROM books b
WHERE b.campus_id = $1 AND b.is_active = true AND b.category = $2
ORDER BY b.title
LIMIT $3 OFFSET $4
`

type GetBooksByCampusAndCategoryParams struct {
	CampusID pgtype.UUID `json:"campus_id"`
	Category string      `json:"category"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type GetBooksByCampusAndCategoryRow struct {
	ID             int16              `json:"id"`
	CampusID       pgtype.UUID        `json:"campus_id"`
	Title          string             `json:"title"`
	Author         string             `json:"author"`
	Category       string             `json:"category"`
	TotalStock     int32              `json:"total_stock"`
	Description    pgtype.Text        `json:"description"`
	IsActive       pgtype.Bool        `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AvailableStock int32              `json:"available_stock"`
}

func (q *Queries) GetBooksByCampusAndCategory(ctx context.Context, arg GetBooksByCampusAndCategoryParams) ([]GetBooksByCampusAndCategoryRow, error) {
	rows, err := q.db.Query(ctx, getBooksByCampusAndCategory,
		arg.CampusID,
		arg.Category,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBooksByCampusAndCategoryRow
	for rows.Next() {
		var i GetBooksByCampusAndCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CampusID,
			&i.Title,
			&i.Author,
			&i.Category,
			&i.TotalStock,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvailableStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCampusByID = `-- name: GetCampusByID :one
SELECT id, short_name, full_name, timezone, is_active, leader_name, leader_form_link, created_at, updated_at FROM campuses WHERE id = $1
`

type GetCampusByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	ShortName      string             `json:"short_name"`
	FullName       string             `json:"full_name"`
	Timezone       pgtype.Text        `json:"timezone"`
	IsActive       bool               `json:"is_active"`
	LeaderName     pgtype.Text        `json:"leader_name"`
	LeaderFormLink pgtype.Text        `json:"leader_form_link"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCampusByID(ctx context.Context, id pgtype.UUID) (GetCampusByIDRow, error) {
	row := q.db.QueryRow(ctx, getCampusByID, id)
	var i GetCampusByIDRow
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.FullName,
		&i.Timezone,
		&i.IsActive,
		&i.LeaderName,
		&i.LeaderFormLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampusByShortName = `-- name: GetCampusByShortName :one
SELECT id, short_name, full_name, timezone, is_active, created_at, updated_at, leader_name, leader_form_link FROM campuses WHERE short_name = $1
`

func (q *Queries) GetCampusByShortName(ctx context.Context, shortName string) (Campuse, error) {
	row := q.db.QueryRow(ctx, getCampusByShortName, shortName)
	var i Campuse
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.FullName,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LeaderName,
		&i.LeaderFormLink,
	)
	return i, err
}

const getCampusesWithBookingsForTimezone = `-- name: GetCampusesWithBookingsForTimezone :many
SELECT DISTINCT c.id, c.short_name, c.full_name, c.timezone
FROM campuses c
INNER JOIN rooms r ON r.campus_id = c.id AND r.is_active = true
INNER JOIN room_bookings rb ON rb.campus_id = c.id AND rb.booking_date = CURRENT_DATE
WHERE (c.timezone = $1 OR EXISTS (
    SELECT 1 FROM registered_users s 
    LEFT JOIN participant_stats_cache psc ON s.s21_login = psc.s21_login
    WHERE psc.campus_id = c.id AND s.timezone = $1
))
AND c.is_active = true
GROUP BY c.id, c.short_name, c.full_name, c.timezone
`

type GetCampusesWithBookingsForTimezoneRow struct {
	ID        pgtype.UUID `json:"id"`
	ShortName string      `json:"short_name"`
	FullName  string      `json:"full_name"`
	Timezone  pgtype.Text `json:"timezone"`
}

func (q *Queries) GetCampusesWithBookingsForTimezone(ctx context.Context, timezone pgtype.Text) ([]GetCampusesWithBookingsForTimezoneRow, error) {
	rows, err := q.db.Query(ctx, getCampusesWithBookingsForTimezone, timezone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCampusesWithBookingsForTimezoneRow
	for rows.Next() {
		var i GetCampusesWithBookingsForTimezoneRow
		if err := rows.Scan(
			&i.ID,
			&i.ShortName,
			&i.FullName,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctUserTimezones = `-- name: GetDistinctUserTimezones :many
SELECT DISTINCT timezone 
FROM registered_users 
WHERE timezone IS NOT NULL AND timezone != ''
ORDER BY timezone
`

func (q *Queries) GetDistinctUserTimezones(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctUserTimezones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var timezone string
		if err := rows.Scan(&timezone); err != nil {
			return nil, err
		}
		items = append(items, timezone)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFSMState = `-- name: GetFSMState :one
SELECT user_id, current_flow, current_state, context, language, updated_at FROM fsm_user_states WHERE user_id = $1
`

func (q *Queries) GetFSMState(ctx context.Context, userID int64) (FsmUserState, error) {
	row := q.db.QueryRow(ctx, getFSMState, userID)
	var i FsmUserState
	err := row.Scan(
		&i.UserID,
		&i.CurrentFlow,
		&i.CurrentState,
		&i.Context,
		&i.Language,
		&i.UpdatedAt,
	)
	return i, err
}

const getGlobalClubs = `-- name: GetGlobalClubs :many
SELECT 
    c.id,
    c.name,
    c.description,
    c.leader_login,
    c.external_link,
    cat.name as category_name,
    c.is_local,
    c.is_active,
    camp.short_name as campus_name
FROM clubs c
JOIN club_categories cat ON c.category_id = cat.id
JOIN campuses camp ON c.campus_id = camp.id
WHERE c.is_active = true AND c.is_local = false
ORDER BY c.name
`

type GetGlobalClubsRow struct {
	ID           int16       `json:"id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	LeaderLogin  pgtype.Text `json:"leader_login"`
	ExternalLink pgtype.Text `json:"external_link"`
	CategoryName string      `json:"category_name"`
	IsLocal      pgtype.Bool `json:"is_local"`
	IsActive     pgtype.Bool `json:"is_active"`
	CampusName   string      `json:"campus_name"`
}

func (q *Queries) GetGlobalClubs(ctx context.Context) ([]GetGlobalClubsRow, error) {
	rows, err := q.db.Query(ctx, getGlobalClubs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGlobalClubsRow
	for rows.Next() {
		var i GetGlobalClubsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LeaderLogin,
			&i.ExternalLink,
			&i.CategoryName,
			&i.IsLocal,
			&i.IsActive,
			&i.CampusName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastAuthVerificationCode = `-- name: GetLastAuthVerificationCode :one
SELECT id, s21_login, code, expires_at, created_at FROM auth_verification_codes
WHERE s21_login = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastAuthVerificationCode(ctx context.Context, s21Login pgtype.Text) (AuthVerificationCode, error) {
	row := q.db.QueryRow(ctx, getLastAuthVerificationCode, s21Login)
	var i AuthVerificationCode
	err := row.Scan(
		&i.ID,
		&i.S21Login,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLocalClubs = `-- name: GetLocalClubs :many
SELECT 
    c.id,
    c.name,
    c.description,
    c.leader_login,
    c.external_link,
    cat.name as category_name,
    c.is_local,
    c.is_active,
    camp.short_name as campus_name
FROM clubs c
JOIN club_categories cat ON c.category_id = cat.id
JOIN campuses camp ON c.campus_id = camp.id
WHERE c.is_active = true AND c.is_local = true AND c.campus_id = $1
ORDER BY c.name
`

type GetLocalClubsRow struct {
	ID           int16       `json:"id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	LeaderLogin  pgtype.Text `json:"leader_login"`
	ExternalLink pgtype.Text `json:"external_link"`
	CategoryName string      `json:"category_name"`
	IsLocal      pgtype.Bool `json:"is_local"`
	IsActive     pgtype.Bool `json:"is_active"`
	CampusName   string      `json:"campus_name"`
}

func (q *Queries) GetLocalClubs(ctx context.Context, campusID pgtype.UUID) ([]GetLocalClubsRow, error) {
	rows, err := q.db.Query(ctx, getLocalClubs, campusID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLocalClubsRow
	for rows.Next() {
		var i GetLocalClubsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LeaderLogin,
			&i.ExternalLink,
			&i.CategoryName,
			&i.IsLocal,
			&i.IsActive,
			&i.CampusName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMyProfile = `-- name: GetMyProfile :one
SELECT
    r.s21_login,
    r.rocketchat_id,
    r.timezone,
    r.alternative_contact,
    r.has_coffee_ban,
    camp.id AS campus_id,
    camp.short_name AS campus_name,
    co.name AS coalition_name,
    c.status,
    c.level,
    c.exp_value,
    c.prp,
    c.crp,
    c.coins,
    c.parallel_name,
    c.class_name,
    c.integrity,
    c.friendliness,
    c.punctuality,
    c.thoroughness
FROM registered_users r
LEFT JOIN participant_stats_cache c ON r.s21_login = c.s21_login
LEFT JOIN campuses camp ON c.campus_id = camp.id
LEFT JOIN coalitions co ON c.coalition_id = co.id
WHERE r.s21_login = $1
`

type GetMyProfileRow struct {
	S21Login           string                `json:"s21_login"`
	RocketchatID       string                `json:"rocketchat_id"`
	Timezone           string                `json:"timezone"`
	AlternativeContact pgtype.Text           `json:"alternative_contact"`
	HasCoffeeBan       pgtype.Bool           `json:"has_coffee_ban"`
	CampusID           pgtype.UUID           `json:"campus_id"`
	CampusName         pgtype.Text           `json:"campus_name"`
	CoalitionName      pgtype.Text           `json:"coalition_name"`
	Status             NullEnumStudentStatus `json:"status"`
	Level              pgtype.Int4           `json:"level"`
	ExpValue           pgtype.Int4           `json:"exp_value"`
	Prp                pgtype.Int4           `json:"prp"`
	Crp                pgtype.Int4           `json:"crp"`
	Coins              pgtype.Int4           `json:"coins"`
	ParallelName       pgtype.Text           `json:"parallel_name"`
	ClassName          pgtype.Text           `json:"class_name"`
	Integrity          pgtype.Float4         `json:"integrity"`
	Friendliness       pgtype.Float4         `json:"friendliness"`
	Punctuality        pgtype.Float4         `json:"punctuality"`
	Thoroughness       pgtype.Float4         `json:"thoroughness"`
}

// Профиль зарегистрированного пользователя: регистрационные данные + статистика из кеша.
func (q *Queries) GetMyProfile(ctx context.Context, s21Login string) (GetMyProfileRow, error) {
	row := q.db.QueryRow(ctx, getMyProfile, s21Login)
	var i GetMyProfileRow
	err := row.Scan(
		&i.S21Login,
		&i.RocketchatID,
		&i.Timezone,
		&i.AlternativeContact,
		&i.HasCoffeeBan,
		&i.CampusID,
		&i.CampusName,
		&i.CoalitionName,
		&i.Status,
		&i.Level,
		&i.ExpValue,
		&i.Prp,
		&i.Crp,
		&i.Coins,
		&i.ParallelName,
		&i.ClassName,
		&i.Integrity,
		&i.Friendliness,
		&i.Punctuality,
		&i.Thoroughness,
	)
	return i, err
}

const getParticipantSkills = `-- name: GetParticipantSkills :many
SELECT s.name, s.category, ss.value
FROM participant_skills ss
JOIN skills s ON ss.skill_id = s.id
WHERE ss.s21_login = $1
`

type GetParticipantSkillsRow struct {
	Name     string      `json:"name"`
	Category pgtype.Text `json:"category"`
	Value    int32       `json:"value"`
}

func (q *Queries) GetParticipantSkills(ctx context.Context, s21Login string) ([]GetParticipantSkillsRow, error) {
	rows, err := q.db.Query(ctx, getParticipantSkills, s21Login)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetParticipantSkillsRow
	for rows.Next() {
		var i GetParticipantSkillsRow
		if err := rows.Scan(&i.Name, &i.Category, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipantStatsCache = `-- name: GetParticipantStatsCache :one
SELECT
    c.s21_login,
    camp.short_name AS campus_name,
    co.name AS coalition_name,
    c.status,
    c.level,
    c.exp_value,
    c.prp,
    c.crp,
    c.coins,
    c.parallel_name,
    c.class_name,
    c.integrity,
    c.friendliness,
    c.punctuality,
    c.thoroughness,
    c.updated_at,
    c.lat_synced_at
FROM participant_stats_cache c
LEFT JOIN campuses camp ON c.campus_id = camp.id
LEFT JOIN coalitions co ON c.coalition_id = co.id
WHERE c.s21_login = $1
`

type GetParticipantStatsCacheRow struct {
	S21Login      string             `json:"s21_login"`
	CampusName    pgtype.Text        `json:"campus_name"`
	CoalitionName pgtype.Text        `json:"coalition_name"`
	Status        EnumStudentStatus  `json:"status"`
	Level         int32              `json:"level"`
	ExpValue      int32              `json:"exp_value"`
	Prp           int32              `json:"prp"`
	Crp           int32              `json:"crp"`
	Coins         int32              `json:"coins"`
	ParallelName  pgtype.Text        `json:"parallel_name"`
	ClassName     pgtype.Text        `json:"class_name"`
	Integrity     pgtype.Float4      `json:"integrity"`
	Friendliness  pgtype.Float4      `json:"friendliness"`
	Punctuality   pgtype.Float4      `json:"punctuality"`
	Thoroughness  pgtype.Float4      `json:"thoroughness"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	LatSyncedAt   pgtype.Timestamptz `json:"lat_synced_at"`
}

func (q *Queries) GetParticipantStatsCache(ctx context.Context, s21Login string) (GetParticipantStatsCacheRow, error) {
	row := q.db.QueryRow(ctx, getParticipantStatsCache, s21Login)
	var i GetParticipantStatsCacheRow
	err := row.Scan(
		&i.S21Login,
		&i.CampusName,
		&i.CoalitionName,
		&i.Status,
		&i.Level,
		&i.ExpValue,
		&i.Prp,
		&i.Crp,
		&i.Coins,
		&i.ParallelName,
		&i.ClassName,
		&i.Integrity,
		&i.Friendliness,
		&i.Punctuality,
		&i.Thoroughness,
		&i.UpdatedAt,
		&i.LatSyncedAt,
	)
	return i, err
}

const getPeerProfile = `-- name: GetPeerProfile :one
SELECT
    c.s21_login,
    COALESCE(ua.username, '') AS telegram_username,
    COALESCE(ua.external_id, '') AS external_id,
    ua.is_searchable,
    camp.short_name AS campus_name,
    co.name AS coalition_name,
    c.status,
    c.level,
    c.exp_value,
    c.prp,
    c.crp,
    c.coins,
    c.parallel_name,
    c.class_name,
    c.integrity,
    c.friendliness,
    c.punctuality,
    c.thoroughness
FROM participant_stats_cache c
LEFT JOIN campuses camp ON c.campus_id = camp.id
LEFT JOIN coalitions co ON c.coalition_id = co.id
LEFT JOIN user_accounts ua ON c.s21_login = ua.s21_login AND ua.platform = 'telegram'
WHERE c.s21_login = $1
`

type GetPeerProfileRow struct {
	S21Login         string            `json:"s21_login"`
	TelegramUsername string            `json:"telegram_username"`
	ExternalID       string            `json:"external_id"`
	IsSearchable     pgtype.Bool       `json:"is_searchable"`
	CampusName       pgtype.Text       `json:"campus_name"`
	CoalitionName    pgtype.Text       `json:"coalition_name"`
	Status           EnumStudentStatus `json:"status"`
	Level            int32             `json:"level"`
	ExpValue         int32             `json:"exp_value"`
	Prp              int32             `json:"prp"`
	Crp              int32             `json:"crp"`
	Coins            int32             `json:"coins"`
	ParallelName     pgtype.Text       `json:"parallel_name"`
	ClassName        pgtype.Text       `json:"class_name"`
	Integrity        pgtype.Float4     `json:"integrity"`
	Friendliness     pgtype.Float4     `json:"friendliness"`
	Punctuality      pgtype.Float4     `json:"punctuality"`
	Thoroughness     pgtype.Float4     `json:"thoroughness"`
}

// Профиль пира: из кеша статистики + telegram username если зарегистрирован.
func (q *Queries) GetPeerProfile(ctx context.Context, s21Login string) (GetPeerProfileRow, error) {
	row := q.db.QueryRow(ctx, getPeerProfile, s21Login)
	var i GetPeerProfileRow
	err := row.Scan(
		&i.S21Login,
		&i.TelegramUsername,
		&i.ExternalID,
		&i.IsSearchable,
		&i.CampusName,
		&i.CoalitionName,
		&i.Status,
		&i.Level,
		&i.ExpValue,
		&i.Prp,
		&i.Crp,
		&i.Coins,
		&i.ParallelName,
		&i.ClassName,
		&i.Integrity,
		&i.Friendliness,
		&i.Punctuality,
		&i.Thoroughness,
	)
	return i, err
}

const getPlatformCredentials = `-- name: GetPlatformCredentials :one
SELECT s21_login, password_enc, password_nonce, access_token, access_expires_at, refresh_token_enc, refresh_nonce, refresh_expires_at, updated_at FROM platform_credentials 
WHERE s21_login = $1
`

func (q *Queries) GetPlatformCredentials(ctx context.Context, s21Login string) (PlatformCredential, error) {
	row := q.db.QueryRow(ctx, getPlatformCredentials, s21Login)
	var i PlatformCredential
	err := row.Scan(
		&i.S21Login,
		&i.PasswordEnc,
		&i.PasswordNonce,
		&i.AccessToken,
		&i.AccessExpiresAt,
		&i.RefreshTokenEnc,
		&i.RefreshNonce,
		&i.RefreshExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegisteredUserByRocketChatId = `-- name: GetRegisteredUserByRocketChatId :one
SELECT s21_login, rocketchat_id, timezone, alternative_contact, has_coffee_ban, created_at, updated_at FROM registered_users WHERE rocketchat_id = $1
`

func (q *Queries) GetRegisteredUserByRocketChatId(ctx context.Context, rocketchatID string) (RegisteredUser, error) {
	row := q.db.QueryRow(ctx, getRegisteredUserByRocketChatId, rocketchatID)
	var i RegisteredUser
	err := row.Scan(
		&i.S21Login,
		&i.RocketchatID,
		&i.Timezone,
		&i.AlternativeContact,
		&i.HasCoffeeBan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegisteredUserByS21Login = `-- name: GetRegisteredUserByS21Login :one

SELECT s21_login, rocketchat_id, timezone, alternative_contact, has_coffee_ban, created_at, updated_at FROM registered_users WHERE s21_login = $1
`

// queries.sql
func (q *Queries) GetRegisteredUserByS21Login(ctx context.Context, s21Login string) (RegisteredUser, error) {
	row := q.db.QueryRow(ctx, getRegisteredUserByS21Login, s21Login)
	var i RegisteredUser
	err := row.Scan(
		&i.S21Login,
		&i.RocketchatID,
		&i.Timezone,
		&i.AlternativeContact,
		&i.HasCoffeeBan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRocketChatCredentials = `-- name: GetRocketChatCredentials :one
SELECT s21_login, rc_token_enc, rc_nonce, updated_at FROM rocketchat_credentials
WHERE s21_login = $1
`

func (q *Queries) GetRocketChatCredentials(ctx context.Context, s21Login string) (RocketchatCredential, error) {
	row := q.db.QueryRow(ctx, getRocketChatCredentials, s21Login)
	var i RocketchatCredential
	err := row.Scan(
		&i.S21Login,
		&i.RcTokenEnc,
		&i.RcNonce,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomBookingsByDate = `-- name: GetRoomBookingsByDate :many
SELECT rb.id, rb.campus_id, rb.room_id, rb.user_id, rb.booking_date, rb.start_time, rb.duration_minutes, rb.created_at, COALESCE(ua.s21_login, 'unknown') as nickname
FROM room_bookings rb
LEFT JOIN user_accounts ua ON rb.user_id = ua.id
WHERE rb.campus_id = $1 AND rb.room_id = $2 AND rb.booking_date = $3
ORDER BY rb.start_time
`

type GetRoomBookingsByDateParams struct {
	CampusID    pgtype.UUID `json:"campus_id"`
	RoomID      int16       `json:"room_id"`
	BookingDate pgtype.Date `json:"booking_date"`
}

type GetRoomBookingsByDateRow struct {
	ID              int64              `json:"id"`
	CampusID        pgtype.UUID        `json:"campus_id"`
	RoomID          int16              `json:"room_id"`
	UserID          int64              `json:"user_id"`
	BookingDate     pgtype.Date        `json:"booking_date"`
	StartTime       pgtype.Time        `json:"start_time"`
	DurationMinutes int32              `json:"duration_minutes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Nickname        string             `json:"nickname"`
}

func (q *Queries) GetRoomBookingsByDate(ctx context.Context, arg GetRoomBookingsByDateParams) ([]GetRoomBookingsByDateRow, error) {
	rows, err := q.db.Query(ctx, getRoomBookingsByDate, arg.CampusID, arg.RoomID, arg.BookingDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomBookingsByDateRow
	for rows.Next() {
		var i GetRoomBookingsByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.CampusID,
			&i.RoomID,
			&i.UserID,
			&i.BookingDate,
			&i.StartTime,
			&i.DurationMinutes,
			&i.CreatedAt,
			&i.Nickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, campus_id, name, min_duration, max_duration, is_active, description, created_at, updated_at, capacity FROM rooms
WHERE campus_id = $1 AND id = $2
`

type GetRoomByIDParams struct {
	CampusID pgtype.UUID `json:"campus_id"`
	ID       int16       `json:"id"`
}

func (q *Queries) GetRoomByID(ctx context.Context, arg GetRoomByIDParams) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, arg.CampusID, arg.ID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.CampusID,
		&i.Name,
		&i.MinDuration,
		&i.MaxDuration,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Capacity,
	)
	return i, err
}

const getUserAccountByExternalId = `-- name: GetUserAccountByExternalId :one
SELECT id, s21_login, platform, external_id, username, is_searchable, role, linked_at FROM user_accounts 
WHERE platform = $1 AND external_id = $2
`

type GetUserAccountByExternalIdParams struct {
	Platform   EnumPlatform `json:"platform"`
	ExternalID string       `json:"external_id"`
}

func (q *Queries) GetUserAccountByExternalId(ctx context.Context, arg GetUserAccountByExternalIdParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByExternalId, arg.Platform, arg.ExternalID)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.S21Login,
		&i.Platform,
		&i.ExternalID,
		&i.Username,
		&i.IsSearchable,
		&i.Role,
		&i.LinkedAt,
	)
	return i, err
}

const getUserAccountByS21Login = `-- name: GetUserAccountByS21Login :one
SELECT id, s21_login, platform, external_id, username, is_searchable, role, linked_at FROM user_accounts
WHERE s21_login = $1
`

func (q *Queries) GetUserAccountByS21Login(ctx context.Context, s21Login string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByS21Login, s21Login)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.S21Login,
		&i.Platform,
		&i.ExternalID,
		&i.Username,
		&i.IsSearchable,
		&i.Role,
		&i.LinkedAt,
	)
	return i, err
}

const getUserActiveLoanCount = `-- name: GetUserActiveLoanCount :one
SELECT count(*)::int 
FROM book_loans 
WHERE user_id = $1 AND returned_at IS NULL
`

func (q *Queries) GetUserActiveLoanCount(ctx context.Context, userID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getUserActiveLoanCount, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserBookLoans = `-- name: GetUserBookLoans :many
SELECT bl.id, bl.campus_id, bl.book_id, bl.user_id, bl.borrowed_at, bl.due_at, bl.returned_at, b.title as book_title, b.author as book_author
FROM book_loans bl
JOIN books b ON bl.campus_id = b.campus_id AND bl.book_id = b.id
WHERE bl.user_id = $1 AND bl.returned_at IS NULL
ORDER BY bl.due_at
`

type GetUserBookLoansRow struct {
	ID         int64              `json:"id"`
	CampusID   pgtype.UUID        `json:"campus_id"`
	BookID     int16              `json:"book_id"`
	UserID     int64              `json:"user_id"`
	BorrowedAt pgtype.Timestamptz `json:"borrowed_at"`
	DueAt      pgtype.Timestamptz `json:"due_at"`
	ReturnedAt pgtype.Timestamptz `json:"returned_at"`
	BookTitle  string             `json:"book_title"`
	BookAuthor string             `json:"book_author"`
}

func (q *Queries) GetUserBookLoans(ctx context.Context, userID int64) ([]GetUserBookLoansRow, error) {
	rows, err := q.db.Query(ctx, getUserBookLoans, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserBookLoansRow
	for rows.Next() {
		var i GetUserBookLoansRow
		if err := rows.Scan(
			&i.ID,
			&i.CampusID,
			&i.BookID,
			&i.UserID,
			&i.BorrowedAt,
			&i.DueAt,
			&i.ReturnedAt,
			&i.BookTitle,
			&i.BookAuthor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBotSettings = `-- name: GetUserBotSettings :one
SELECT id, user_account_id, language_code, notifications_enabled, review_post_campus_ids, created_at, updated_at FROM user_bot_settings 
WHERE user_account_id = $1
`

func (q *Queries) GetUserBotSettings(ctx context.Context, userAccountID int64) (UserBotSetting, error) {
	row := q.db.QueryRow(ctx, getUserBotSettings, userAccountID)
	var i UserBotSetting
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.LanguageCode,
		&i.NotificationsEnabled,
		&i.ReviewPostCampusIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoomBookings = `-- name: GetUserRoomBookings :many
SELECT rb.id, rb.campus_id, rb.room_id, rb.user_id, rb.booking_date, rb.start_time, rb.duration_minutes, rb.created_at, r.name as room_name, c.short_name as campus_short_name
FROM room_bookings rb
JOIN rooms r ON rb.campus_id = r.campus_id AND rb.room_id = r.id
JOIN campuses c ON rb.campus_id = c.id
WHERE rb.user_id = $1 AND rb.booking_date >= CURRENT_DATE
ORDER BY rb.booking_date, rb.start_time
`

type GetUserRoomBookingsRow struct {
	ID              int64              `json:"id"`
	CampusID        pgtype.UUID        `json:"campus_id"`
	RoomID          int16              `json:"room_id"`
	UserID          int64              `json:"user_id"`
	BookingDate     pgtype.Date        `json:"booking_date"`
	StartTime       pgtype.Time        `json:"start_time"`
	DurationMinutes int32              `json:"duration_minutes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	RoomName        string             `json:"room_name"`
	CampusShortName string             `json:"campus_short_name"`
}

func (q *Queries) GetUserRoomBookings(ctx context.Context, userID int64) ([]GetUserRoomBookingsRow, error) {
	rows, err := q.db.Query(ctx, getUserRoomBookings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRoomBookingsRow
	for rows.Next() {
		var i GetUserRoomBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampusID,
			&i.RoomID,
			&i.UserID,
			&i.BookingDate,
			&i.StartTime,
			&i.DurationMinutes,
			&i.CreatedAt,
			&i.RoomName,
			&i.CampusShortName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidAuthVerificationCode = `-- name: GetValidAuthVerificationCode :one
SELECT id, s21_login, code, expires_at, created_at FROM auth_verification_codes
WHERE s21_login = $1 AND code = $2 AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC
LIMIT 1
`

type GetValidAuthVerificationCodeParams struct {
	S21Login pgtype.Text `json:"s21_login"`
	Code     string      `json:"code"`
}

func (q *Queries) GetValidAuthVerificationCode(ctx context.Context, arg GetValidAuthVerificationCodeParams) (AuthVerificationCode, error) {
	row := q.db.QueryRow(ctx, getValidAuthVerificationCode, arg.S21Login, arg.Code)
	var i AuthVerificationCode
	err := row.Scan(
		&i.ID,
		&i.S21Login,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const hasActiveBooks = `-- name: HasActiveBooks :one
SELECT EXISTS(SELECT 1 FROM books WHERE campus_id = $1 AND is_active = true)
`

func (q *Queries) HasActiveBooks(ctx context.Context, campusID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveBooks, campusID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasActiveRooms = `-- name: HasActiveRooms :one
SELECT EXISTS(SELECT 1 FROM rooms WHERE campus_id = $1 AND is_active = true)
`

func (q *Queries) HasActiveRooms(ctx context.Context, campusID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveRooms, campusID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const returnBookLoan = `-- name: ReturnBookLoan :exec
UPDATE book_loans
SET returned_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2 AND returned_at IS NULL
`

type ReturnBookLoanParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) ReturnBookLoan(ctx context.Context, arg ReturnBookLoanParams) error {
	_, err := q.db.Exec(ctx, returnBookLoan, arg.ID, arg.UserID)
	return err
}

const revokeOldApiKeys = `-- name: RevokeOldApiKeys :exec
UPDATE api_keys
SET revoked_at = CURRENT_TIMESTAMP
WHERE user_account_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeOldApiKeys(ctx context.Context, userAccountID int64) error {
	_, err := q.db.Exec(ctx, revokeOldApiKeys, userAccountID)
	return err
}

const searchBooks = `-- name: SearchBooks :many
SELECT b.id, b.campus_id, b.title, b.author, b.category, b.total_stock, b.description, b.is_active, b.created_at, b.updated_at,
       (b.total_stock - (SELECT count(*) FROM book_loans bl WHERE bl.campus_id = b.campus_id AND bl.book_id = b.id AND bl.returned_at IS NULL))::int as available_stock
FROM books b
WHERE b.campus_id = $1 AND b.is_active = true AND (b.title ILIKE '%' || $2 || '%' OR b.author ILIKE '%' || $2 || '%')
ORDER BY b.title
LIMIT $3 OFFSET $4
`

type SearchBooksParams struct {
	CampusID pgtype.UUID `json:"campus_id"`
	Column2  pgtype.Text `json:"column_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type SearchBooksRow struct {
	ID             int16              `json:"id"`
	CampusID       pgtype.UUID        `json:"campus_id"`
	Title          string             `json:"title"`
	Author         string             `json:"author"`
	Category       string             `json:"category"`
	TotalStock     int32              `json:"total_stock"`
	Description    pgtype.Text        `json:"description"`
	IsActive       pgtype.Bool        `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AvailableStock int32              `json:"available_stock"`
}

func (q *Queries) SearchBooks(ctx context.Context, arg SearchBooksParams) ([]SearchBooksRow, error) {
	rows, err := q.db.Query(ctx, searchBooks,
		arg.CampusID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBooksRow
	for rows.Next() {
		var i SearchBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.CampusID,
			&i.Title,
			&i.Author,
			&i.Category,
			&i.TotalStock,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvailableStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoomBookingDuration = `-- name: UpdateRoomBookingDuration :exec
UPDATE room_bookings
SET duration_minutes = $3
WHERE id = $1 AND user_id = $2
`

type UpdateRoomBookingDurationParams struct {
	ID              int64 `json:"id"`
	UserID          int64 `json:"user_id"`
	DurationMinutes int32 `json:"duration_minutes"`
}

func (q *Queries) UpdateRoomBookingDuration(ctx context.Context, arg UpdateRoomBookingDurationParams) error {
	_, err := q.db.Exec(ctx, updateRoomBookingDuration, arg.ID, arg.UserID, arg.DurationMinutes)
	return err
}

const upsertBook = `-- name: UpsertBook :one
INSERT INTO books (
    id, campus_id, title, author, category, total_stock, description, is_active, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, CURRENT_TIMESTAMP
)
ON CONFLICT (campus_id, id) DO UPDATE SET
    title = EXCLUDED.title,
    author = EXCLUDED.author,
    category = EXCLUDED.category,
    total_stock = EXCLUDED.total_stock,
    description = EXCLUDED.description,
    is_active = EXCLUDED.is_active,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, campus_id, title, author, category, total_stock, description, is_active, created_at, updated_at
`

type UpsertBookParams struct {
	ID          int16       `json:"id"`
	CampusID    pgtype.UUID `json:"campus_id"`
	Title       string      `json:"title"`
	Author      string      `json:"author"`
	Category    string      `json:"category"`
	TotalStock  int32       `json:"total_stock"`
	Description pgtype.Text `json:"description"`
	IsActive    pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpsertBook(ctx context.Context, arg UpsertBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, upsertBook,
		arg.ID,
		arg.CampusID,
		arg.Title,
		arg.Author,
		arg.Category,
		arg.TotalStock,
		arg.Description,
		arg.IsActive,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.CampusID,
		&i.Title,
		&i.Author,
		&i.Category,
		&i.TotalStock,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCampus = `-- name: UpsertCampus :one
INSERT INTO campuses (id, short_name, full_name, timezone, is_active, leader_name, leader_form_link)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    short_name = EXCLUDED.short_name,
    full_name = EXCLUDED.full_name,
    timezone = EXCLUDED.timezone,
    is_active = EXCLUDED.is_active,
    leader_name = COALESCE(EXCLUDED.leader_name, campuses.leader_name),
    leader_form_link = COALESCE(EXCLUDED.leader_form_link, campuses.leader_form_link),
    updated_at = CURRENT_TIMESTAMP
RETURNING id, short_name, full_name, timezone, is_active, created_at, updated_at, leader_name, leader_form_link
`

type UpsertCampusParams struct {
	ID             pgtype.UUID `json:"id"`
	ShortName      string      `json:"short_name"`
	FullName       string      `json:"full_name"`
	Timezone       pgtype.Text `json:"timezone"`
	IsActive       bool        `json:"is_active"`
	LeaderName     pgtype.Text `json:"leader_name"`
	LeaderFormLink pgtype.Text `json:"leader_form_link"`
}

func (q *Queries) UpsertCampus(ctx context.Context, arg UpsertCampusParams) (Campuse, error) {
	row := q.db.QueryRow(ctx, upsertCampus,
		arg.ID,
		arg.ShortName,
		arg.FullName,
		arg.Timezone,
		arg.IsActive,
		arg.LeaderName,
		arg.LeaderFormLink,
	)
	var i Campuse
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.FullName,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LeaderName,
		&i.LeaderFormLink,
	)
	return i, err
}

const upsertClub = `-- name: UpsertClub :one
INSERT INTO clubs (
    id, campus_id, leader_login, name, description, category_id,
    external_link, is_local, is_active, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, CURRENT_TIMESTAMP
)
ON CONFLICT (campus_id, id) DO UPDATE SET
    leader_login = EXCLUDED.leader_login,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    category_id = EXCLUDED.category_id,
    external_link = EXCLUDED.external_link,
    is_local = EXCLUDED.is_local,
    is_active = EXCLUDED.is_active,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, campus_id, leader_login, name, description, category_id, external_link, is_local, is_active, created_at, updated_at
`

type UpsertClubParams struct {
	ID           int16       `json:"id"`
	CampusID     pgtype.UUID `json:"campus_id"`
	LeaderLogin  pgtype.Text `json:"leader_login"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	CategoryID   int16       `json:"category_id"`
	ExternalLink pgtype.Text `json:"external_link"`
	IsLocal      pgtype.Bool `json:"is_local"`
	IsActive     pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpsertClub(ctx context.Context, arg UpsertClubParams) (Club, error) {
	row := q.db.QueryRow(ctx, upsertClub,
		arg.ID,
		arg.CampusID,
		arg.LeaderLogin,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.ExternalLink,
		arg.IsLocal,
		arg.IsActive,
	)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.CampusID,
		&i.LeaderLogin,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.ExternalLink,
		&i.IsLocal,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertClubCategory = `-- name: UpsertClubCategory :one
INSERT INTO club_categories (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET
    name = EXCLUDED.name
RETURNING id, name, created_at
`

func (q *Queries) UpsertClubCategory(ctx context.Context, name string) (ClubCategory, error) {
	row := q.db.QueryRow(ctx, upsertClubCategory, name)
	var i ClubCategory
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const upsertCoalition = `-- name: UpsertCoalition :exec
INSERT INTO coalitions (id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name
`

type UpsertCoalitionParams struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpsertCoalition(ctx context.Context, arg UpsertCoalitionParams) error {
	_, err := q.db.Exec(ctx, upsertCoalition, arg.ID, arg.Name)
	return err
}

const upsertFSMState = `-- name: UpsertFSMState :exec
INSERT INTO fsm_user_states (
    user_id, current_flow, current_state, context, language
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (user_id) DO UPDATE SET
    current_flow = EXCLUDED.current_flow,
    current_state = EXCLUDED.current_state,
    context = EXCLUDED.context,
    language = EXCLUDED.language,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertFSMStateParams struct {
	UserID       int64  `json:"user_id"`
	CurrentFlow  string `json:"current_flow"`
	CurrentState string `json:"current_state"`
	Context      []byte `json:"context"`
	Language     string `json:"language"`
}

func (q *Queries) UpsertFSMState(ctx context.Context, arg UpsertFSMStateParams) error {
	_, err := q.db.Exec(ctx, upsertFSMState,
		arg.UserID,
		arg.CurrentFlow,
		arg.CurrentState,
		arg.Context,
		arg.Language,
	)
	return err
}

const upsertParticipantSkill = `-- name: UpsertParticipantSkill :exec
INSERT INTO participant_skills (s21_login, skill_id, value)
VALUES ($1, $2, $3)
ON CONFLICT (s21_login, skill_id) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertParticipantSkillParams struct {
	S21Login string `json:"s21_login"`
	SkillID  int32  `json:"skill_id"`
	Value    int32  `json:"value"`
}

func (q *Queries) UpsertParticipantSkill(ctx context.Context, arg UpsertParticipantSkillParams) error {
	_, err := q.db.Exec(ctx, upsertParticipantSkill, arg.S21Login, arg.SkillID, arg.Value)
	return err
}

const upsertParticipantStatsCache = `-- name: UpsertParticipantStatsCache :exec
INSERT INTO participant_stats_cache (
    s21_login, campus_id, coalition_id, status, level, exp_value,
    prp, crp, coins, parallel_name, class_name,
    integrity, friendliness, punctuality, thoroughness,
    lat_synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
    CURRENT_TIMESTAMP
)
ON CONFLICT (s21_login) DO UPDATE SET
    campus_id = EXCLUDED.campus_id,
    coalition_id = EXCLUDED.coalition_id,
    status = EXCLUDED.status,
    level = EXCLUDED.level,
    exp_value = EXCLUDED.exp_value,
    prp = EXCLUDED.prp,
    crp = EXCLUDED.crp,
    coins = EXCLUDED.coins,
    parallel_name = EXCLUDED.parallel_name,
    class_name = EXCLUDED.class_name,
    integrity = EXCLUDED.integrity,
    friendliness = EXCLUDED.friendliness,
    punctuality = EXCLUDED.punctuality,
    thoroughness = EXCLUDED.thoroughness,
    updated_at = CURRENT_TIMESTAMP,
    lat_synced_at = CURRENT_TIMESTAMP
`

type UpsertParticipantStatsCacheParams struct {
	S21Login     string            `json:"s21_login"`
	CampusID     pgtype.UUID       `json:"campus_id"`
	CoalitionID  pgtype.Int2       `json:"coalition_id"`
	Status       EnumStudentStatus `json:"status"`
	Level        int32             `json:"level"`
	ExpValue     int32             `json:"exp_value"`
	Prp          int32             `json:"prp"`
	Crp          int32             `json:"crp"`
	Coins        int32             `json:"coins"`
	ParallelName pgtype.Text       `json:"parallel_name"`
	ClassName    pgtype.Text       `json:"class_name"`
	Integrity    pgtype.Float4     `json:"integrity"`
	Friendliness pgtype.Float4     `json:"friendliness"`
	Punctuality  pgtype.Float4     `json:"punctuality"`
	Thoroughness pgtype.Float4     `json:"thoroughness"`
}

func (q *Queries) UpsertParticipantStatsCache(ctx context.Context, arg UpsertParticipantStatsCacheParams) error {
	_, err := q.db.Exec(ctx, upsertParticipantStatsCache,
		arg.S21Login,
		arg.CampusID,
		arg.CoalitionID,
		arg.Status,
		arg.Level,
		arg.ExpValue,
		arg.Prp,
		arg.Crp,
		arg.Coins,
		arg.ParallelName,
		arg.ClassName,
		arg.Integrity,
		arg.Friendliness,
		arg.Punctuality,
		arg.Thoroughness,
	)
	return err
}

const upsertPlatformCredentials = `-- name: UpsertPlatformCredentials :exec
INSERT INTO platform_credentials (
    s21_login, password_enc, password_nonce, 
    access_token, access_expires_at, refresh_token_enc, 
    refresh_nonce, refresh_expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (s21_login) DO UPDATE SET
    password_enc = EXCLUDED.password_enc,
    password_nonce = EXCLUDED.password_nonce,
    access_token = EXCLUDED.access_token,
    access_expires_at = EXCLUDED.access_expires_at,
    refresh_token_enc = EXCLUDED.refresh_token_enc,
    refresh_nonce = EXCLUDED.refresh_nonce,
    refresh_expires_at = EXCLUDED.refresh_expires_at,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertPlatformCredentialsParams struct {
	S21Login         string             `json:"s21_login"`
	PasswordEnc      []byte             `json:"password_enc"`
	PasswordNonce    []byte             `json:"password_nonce"`
	AccessToken      pgtype.Text        `json:"access_token"`
	AccessExpiresAt  pgtype.Timestamptz `json:"access_expires_at"`
	RefreshTokenEnc  []byte             `json:"refresh_token_enc"`
	RefreshNonce     []byte             `json:"refresh_nonce"`
	RefreshExpiresAt pgtype.Timestamptz `json:"refresh_expires_at"`
}

func (q *Queries) UpsertPlatformCredentials(ctx context.Context, arg UpsertPlatformCredentialsParams) error {
	_, err := q.db.Exec(ctx, upsertPlatformCredentials,
		arg.S21Login,
		arg.PasswordEnc,
		arg.PasswordNonce,
		arg.AccessToken,
		arg.AccessExpiresAt,
		arg.RefreshTokenEnc,
		arg.RefreshNonce,
		arg.RefreshExpiresAt,
	)
	return err
}

const upsertRegisteredUser = `-- name: UpsertRegisteredUser :one
INSERT INTO registered_users (
    s21_login, rocketchat_id,
    timezone, alternative_contact, has_coffee_ban
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (s21_login) DO UPDATE SET
    rocketchat_id = COALESCE(EXCLUDED.rocketchat_id, registered_users.rocketchat_id),
    timezone = COALESCE(EXCLUDED.timezone, registered_users.timezone),
    alternative_contact = COALESCE(EXCLUDED.alternative_contact, registered_users.alternative_contact),
    has_coffee_ban = COALESCE(EXCLUDED.has_coffee_ban, registered_users.has_coffee_ban),
    updated_at = CURRENT_TIMESTAMP
RETURNING s21_login, rocketchat_id, timezone, alternative_contact, has_coffee_ban, created_at, updated_at
`

type UpsertRegisteredUserParams struct {
	S21Login           string      `json:"s21_login"`
	RocketchatID       string      `json:"rocketchat_id"`
	Timezone           string      `json:"timezone"`
	AlternativeContact pgtype.Text `json:"alternative_contact"`
	HasCoffeeBan       pgtype.Bool `json:"has_coffee_ban"`
}

func (q *Queries) UpsertRegisteredUser(ctx context.Context, arg UpsertRegisteredUserParams) (RegisteredUser, error) {
	row := q.db.QueryRow(ctx, upsertRegisteredUser,
		arg.S21Login,
		arg.RocketchatID,
		arg.Timezone,
		arg.AlternativeContact,
		arg.HasCoffeeBan,
	)
	var i RegisteredUser
	err := row.Scan(
		&i.S21Login,
		&i.RocketchatID,
		&i.Timezone,
		&i.AlternativeContact,
		&i.HasCoffeeBan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRocketChatCredentials = `-- name: UpsertRocketChatCredentials :exec
INSERT INTO rocketchat_credentials (
    s21_login, rc_token_enc, rc_nonce
) VALUES (
    $1, $2, $3
)
ON CONFLICT (s21_login) DO UPDATE SET
    rc_token_enc = EXCLUDED.rc_token_enc,
    rc_nonce = EXCLUDED.rc_nonce,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertRocketChatCredentialsParams struct {
	S21Login   string `json:"s21_login"`
	RcTokenEnc []byte `json:"rc_token_enc"`
	RcNonce    []byte `json:"rc_nonce"`
}

func (q *Queries) UpsertRocketChatCredentials(ctx context.Context, arg UpsertRocketChatCredentialsParams) error {
	_, err := q.db.Exec(ctx, upsertRocketChatCredentials, arg.S21Login, arg.RcTokenEnc, arg.RcNonce)
	return err
}

const upsertRoom = `-- name: UpsertRoom :one
INSERT INTO rooms (
    id, campus_id, name, min_duration, max_duration, is_active, description, capacity, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, CURRENT_TIMESTAMP
)
ON CONFLICT (campus_id, id) DO UPDATE SET
    name = EXCLUDED.name,
    min_duration = EXCLUDED.min_duration,
    max_duration = EXCLUDED.max_duration,
    is_active = EXCLUDED.is_active,
    description = EXCLUDED.description,
    capacity = EXCLUDED.capacity,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, campus_id, name, min_duration, max_duration, is_active, description, created_at, updated_at, capacity
`

type UpsertRoomParams struct {
	ID          int16       `json:"id"`
	CampusID    pgtype.UUID `json:"campus_id"`
	Name        string      `json:"name"`
	MinDuration int32       `json:"min_duration"`
	MaxDuration int32       `json:"max_duration"`
	IsActive    pgtype.Bool `json:"is_active"`
	Description pgtype.Text `json:"description"`
	Capacity    int32       `json:"capacity"`
}

func (q *Queries) UpsertRoom(ctx context.Context, arg UpsertRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, upsertRoom,
		arg.ID,
		arg.CampusID,
		arg.Name,
		arg.MinDuration,
		arg.MaxDuration,
		arg.IsActive,
		arg.Description,
		arg.Capacity,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.CampusID,
		&i.Name,
		&i.MinDuration,
		&i.MaxDuration,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Capacity,
	)
	return i, err
}

const upsertSkill = `-- name: UpsertSkill :one
INSERT INTO skills (id, name, category)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE SET
    category = EXCLUDED.category,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, name, category, created_at, updated_at
`

type UpsertSkillParams struct {
	ID       int32       `json:"id"`
	Name     string      `json:"name"`
	Category pgtype.Text `json:"category"`
}

func (q *Queries) UpsertSkill(ctx context.Context, arg UpsertSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, upsertSkill, arg.ID, arg.Name, arg.Category)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserBotSettings = `-- name: UpsertUserBotSettings :one
INSERT INTO user_bot_settings (
    user_account_id, language_code, notifications_enabled, review_post_campus_ids
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (user_account_id) DO UPDATE SET
    language_code = EXCLUDED.language_code,
    notifications_enabled = EXCLUDED.notifications_enabled,
    review_post_campus_ids = EXCLUDED.review_post_campus_ids,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_account_id, language_code, notifications_enabled, review_post_campus_ids, created_at, updated_at
`

type UpsertUserBotSettingsParams struct {
	UserAccountID        int64       `json:"user_account_id"`
	LanguageCode         pgtype.Text `json:"language_code"`
	NotificationsEnabled pgtype.Bool `json:"notifications_enabled"`
	ReviewPostCampusIds  []byte      `json:"review_post_campus_ids"`
}

func (q *Queries) UpsertUserBotSettings(ctx context.Context, arg UpsertUserBotSettingsParams) (UserBotSetting, error) {
	row := q.db.QueryRow(ctx, upsertUserBotSettings,
		arg.UserAccountID,
		arg.LanguageCode,
		arg.NotificationsEnabled,
		arg.ReviewPostCampusIds,
	)
	var i UserBotSetting
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.LanguageCode,
		&i.NotificationsEnabled,
		&i.ReviewPostCampusIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
