// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error)
	CreateAuthVerificationCode(ctx context.Context, arg CreateAuthVerificationCodeParams) (AuthVerificationCode, error)
	CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (UserAccount, error)
	DeleteAllAuthVerificationCodes(ctx context.Context, studentID pgtype.Text) error
	DeleteAuthVerificationCode(ctx context.Context, arg DeleteAuthVerificationCodeParams) error
	DeleteExpiredAuthVerificationCodes(ctx context.Context) error
	GetActiveApiKey(ctx context.Context, userAccountID int64) (ApiKey, error)
	GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetFSMState(ctx context.Context, userID int64) (FsmUserState, error)
	GetLastAuthVerificationCode(ctx context.Context, studentID pgtype.Text) (AuthVerificationCode, error)
	GetPlatformCredentials(ctx context.Context, studentID string) (PlatformCredential, error)
	GetRocketChatCredentials(ctx context.Context, studentID string) (RocketchatCredential, error)
	GetStudentByRocketChatId(ctx context.Context, rocketchatID string) (Student, error)
	// queries.sql
	GetStudentByS21Login(ctx context.Context, s21Login string) (Student, error)
	GetStudentProfile(ctx context.Context, s21Login string) (GetStudentProfileRow, error)
	GetUserAccountByExternalId(ctx context.Context, arg GetUserAccountByExternalIdParams) (UserAccount, error)
	GetUserAccountByStudentId(ctx context.Context, studentID string) (UserAccount, error)
	GetUserBotSettings(ctx context.Context, userAccountID int64) (UserBotSetting, error)
	GetValidAuthVerificationCode(ctx context.Context, arg GetValidAuthVerificationCodeParams) (AuthVerificationCode, error)
	RevokeOldApiKeys(ctx context.Context, userAccountID int64) error
	UpsertFSMState(ctx context.Context, arg UpsertFSMStateParams) error
	UpsertPlatformCredentials(ctx context.Context, arg UpsertPlatformCredentialsParams) error
	UpsertRocketChatCredentials(ctx context.Context, arg UpsertRocketChatCredentialsParams) error
	UpsertStudent(ctx context.Context, arg UpsertStudentParams) (Student, error)
	UpsertUserBotSettings(ctx context.Context, arg UpsertUserBotSettingsParams) (UserBotSetting, error)
}

var _ Querier = (*Queries)(nil)
