// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelRoomBooking(ctx context.Context, arg CancelRoomBookingParams) error
	CloseReviewRequestByID(ctx context.Context, id int64) error
	CountBooksByCampus(ctx context.Context, campusID pgtype.UUID) (CountBooksByCampusRow, error)
	CountBooksByCategory(ctx context.Context, arg CountBooksByCategoryParams) (int32, error)
	CountOpenReviewRequestsByUser(ctx context.Context, requesterUserID int64) (int32, error)
	CountSearchBooks(ctx context.Context, arg CountSearchBooksParams) (int32, error)
	CountSearchCatalogProjects(ctx context.Context, dollar_1 interface{}) (int32, error)
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error)
	CreateAuthVerificationCode(ctx context.Context, arg CreateAuthVerificationCodeParams) (AuthVerificationCode, error)
	CreateBookLoan(ctx context.Context, arg CreateBookLoanParams) (BookLoan, error)
	CreateReviewRequest(ctx context.Context, arg CreateReviewRequestParams) (ReviewRequest, error)
	CreateRoomBooking(ctx context.Context, arg CreateRoomBookingParams) (RoomBooking, error)
	CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (UserAccount, error)
	DeactivateBooksByCampus(ctx context.Context, campusID pgtype.UUID) error
	DeactivateClubsByCampus(ctx context.Context, campusID pgtype.UUID) error
	DeactivateRoomsByCampus(ctx context.Context, campusID pgtype.UUID) error
	DeleteAllAuthVerificationCodes(ctx context.Context, s21Login pgtype.Text) error
	DeleteAuthVerificationCode(ctx context.Context, arg DeleteAuthVerificationCodeParams) error
	DeleteExpiredAuthVerificationCodes(ctx context.Context) error
	DeleteStaleCoursesCatalog(ctx context.Context, syncBatchID int64) error
	DeleteStaleNodesCatalog(ctx context.Context, syncBatchID int64) error
	DeleteStaleProjectNodesCatalog(ctx context.Context, syncBatchID int64) error
	DeleteStaleProjectSearchCatalog(ctx context.Context, syncBatchID int64) error
	DeleteStaleProjectsCatalog(ctx context.Context, syncBatchID int64) error
	DeleteUserAccountByExternalId(ctx context.Context, arg DeleteUserAccountByExternalIdParams) error
	ExistsOpenReviewRequestByUserAndProject(ctx context.Context, arg ExistsOpenReviewRequestByUserAndProjectParams) (bool, error)
	GetActiveApiKey(ctx context.Context, userAccountID int64) (ApiKey, error)
	GetActiveRoomsByCampus(ctx context.Context, campusID pgtype.UUID) ([]Room, error)
	GetAllActiveCampuses(ctx context.Context) ([]GetAllActiveCampusesRow, error)
	GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetBookAuthors(ctx context.Context, campusID pgtype.UUID) ([]string, error)
	GetBookByID(ctx context.Context, arg GetBookByIDParams) (GetBookByIDRow, error)
	GetBookCategories(ctx context.Context, campusID pgtype.UUID) ([]string, error)
	GetBooksByCampus(ctx context.Context, arg GetBooksByCampusParams) ([]GetBooksByCampusRow, error)
	GetBooksByCampusAndAuthor(ctx context.Context, arg GetBooksByCampusAndAuthorParams) ([]GetBooksByCampusAndAuthorRow, error)
	GetBooksByCampusAndCategory(ctx context.Context, arg GetBooksByCampusAndCategoryParams) ([]GetBooksByCampusAndCategoryRow, error)
	GetCampusByID(ctx context.Context, id pgtype.UUID) (GetCampusByIDRow, error)
	GetCampusByShortName(ctx context.Context, shortName string) (Campuse, error)
	GetCampusesWithBookingsForTimezone(ctx context.Context, timezone pgtype.Text) ([]GetCampusesWithBookingsForTimezoneRow, error)
	GetCatalogProjectIDsByCourse(ctx context.Context, courseID pgtype.Int8) ([]int64, error)
	GetCatalogProjectIDsByNodeRecursive(ctx context.Context, id int64) ([]int64, error)
	GetCatalogProjectTitlesByIDs(ctx context.Context, dollar_1 []int64) ([]GetCatalogProjectTitlesByIDsRow, error)
	GetDistinctUserTimezones(ctx context.Context) ([]string, error)
	GetFSMState(ctx context.Context, userID int64) (FsmUserState, error)
	GetGlobalClubs(ctx context.Context) ([]GetGlobalClubsRow, error)
	GetGlobalReviewProjectGroups(ctx context.Context) ([]GetGlobalReviewProjectGroupsRow, error)
	GetLastAuthVerificationCode(ctx context.Context, s21Login pgtype.Text) (AuthVerificationCode, error)
	GetLocalClubs(ctx context.Context, campusID pgtype.UUID) ([]GetLocalClubsRow, error)
	GetMyOpenReviewRequests(ctx context.Context, requesterUserID int64) ([]GetMyOpenReviewRequestsRow, error)
	// Профиль зарегистрированного пользователя: регистрационные данные + статистика из кеша.
	GetMyProfile(ctx context.Context, s21Login string) (GetMyProfileRow, error)
	GetMyReviewRequestByID(ctx context.Context, arg GetMyReviewRequestByIDParams) (GetMyReviewRequestByIDRow, error)
	GetOpenReviewRequestsByProject(ctx context.Context, projectID int64) ([]GetOpenReviewRequestsByProjectRow, error)
	GetParticipantSkills(ctx context.Context, s21Login string) ([]GetParticipantSkillsRow, error)
	GetParticipantStatsCache(ctx context.Context, s21Login string) (GetParticipantStatsCacheRow, error)
	// Профиль пира: из кеша статистики + telegram username если зарегистрирован.
	GetPeerProfile(ctx context.Context, s21Login string) (GetPeerProfileRow, error)
	GetPlatformCredentials(ctx context.Context, s21Login string) (PlatformCredential, error)
	GetRegisteredUserByRocketChatId(ctx context.Context, rocketchatID string) (RegisteredUser, error)
	// queries.sql
	GetRegisteredUserByS21Login(ctx context.Context, s21Login string) (RegisteredUser, error)
	GetReviewRequestByID(ctx context.Context, id int64) (GetReviewRequestByIDRow, error)
	GetReviewRequestsForCleanup(ctx context.Context, arg GetReviewRequestsForCleanupParams) ([]GetReviewRequestsForCleanupRow, error)
	GetRocketChatCredentials(ctx context.Context, s21Login string) (RocketchatCredential, error)
	GetRoomBookingsByDate(ctx context.Context, arg GetRoomBookingsByDateParams) ([]GetRoomBookingsByDateRow, error)
	GetRoomByID(ctx context.Context, arg GetRoomByIDParams) (Room, error)
	GetUserAccountByExternalId(ctx context.Context, arg GetUserAccountByExternalIdParams) (UserAccount, error)
	GetUserAccountByID(ctx context.Context, id int64) (UserAccount, error)
	GetUserAccountByS21Login(ctx context.Context, s21Login string) (UserAccount, error)
	GetUserActiveLoanCount(ctx context.Context, userID int64) (int32, error)
	GetUserBookLoans(ctx context.Context, userID int64) ([]GetUserBookLoansRow, error)
	GetUserBotSettings(ctx context.Context, userAccountID int64) (UserBotSetting, error)
	GetUserRoomBookings(ctx context.Context, userID int64) ([]GetUserRoomBookingsRow, error)
	GetValidAuthVerificationCode(ctx context.Context, arg GetValidAuthVerificationCodeParams) (AuthVerificationCode, error)
	HasActiveBooks(ctx context.Context, campusID pgtype.UUID) (bool, error)
	HasActiveRooms(ctx context.Context, campusID pgtype.UUID) (bool, error)
	IncrementReviewRequestViewCount(ctx context.Context, id int64) (int32, error)
	MarkReviewRequestNegotiatingAndIncrementResponses(ctx context.Context, arg MarkReviewRequestNegotiatingAndIncrementResponsesParams) (MarkReviewRequestNegotiatingAndIncrementResponsesRow, error)
	ReturnBookLoan(ctx context.Context, arg ReturnBookLoanParams) error
	RevokeOldApiKeys(ctx context.Context, userAccountID int64) error
	SearchBooks(ctx context.Context, arg SearchBooksParams) ([]SearchBooksRow, error)
	SearchCatalogCourses(ctx context.Context, dollar_1 interface{}) ([]SearchCatalogCoursesRow, error)
	SearchCatalogNodes(ctx context.Context, dollar_1 interface{}) ([]SearchCatalogNodesRow, error)
	SearchCatalogProjects(ctx context.Context, arg SearchCatalogProjectsParams) ([]SearchCatalogProjectsRow, error)
	SearchCatalogProjectsAll(ctx context.Context, dollar_1 interface{}) ([]SearchCatalogProjectsAllRow, error)
	SetReviewRequestStatus(ctx context.Context, arg SetReviewRequestStatusParams) (SetReviewRequestStatusRow, error)
	UpdateRoomBookingDuration(ctx context.Context, arg UpdateRoomBookingDurationParams) error
	UpdateUserAccountSearchableByExternalId(ctx context.Context, arg UpdateUserAccountSearchableByExternalIdParams) (UserAccount, error)
	UpsertBook(ctx context.Context, arg UpsertBookParams) (Book, error)
	UpsertCampus(ctx context.Context, arg UpsertCampusParams) (Campuse, error)
	UpsertClub(ctx context.Context, arg UpsertClubParams) (Club, error)
	UpsertClubCategory(ctx context.Context, name string) (ClubCategory, error)
	UpsertCoalition(ctx context.Context, arg UpsertCoalitionParams) error
	UpsertCourseCatalog(ctx context.Context, arg UpsertCourseCatalogParams) error
	UpsertFSMState(ctx context.Context, arg UpsertFSMStateParams) error
	UpsertNodeCatalog(ctx context.Context, arg UpsertNodeCatalogParams) (int64, error)
	UpsertParticipantSkill(ctx context.Context, arg UpsertParticipantSkillParams) error
	UpsertParticipantStatsCache(ctx context.Context, arg UpsertParticipantStatsCacheParams) error
	UpsertPlatformCredentials(ctx context.Context, arg UpsertPlatformCredentialsParams) error
	UpsertProjectCatalog(ctx context.Context, arg UpsertProjectCatalogParams) error
	UpsertProjectNodeCatalog(ctx context.Context, arg UpsertProjectNodeCatalogParams) error
	UpsertRegisteredUser(ctx context.Context, arg UpsertRegisteredUserParams) (RegisteredUser, error)
	UpsertRocketChatCredentials(ctx context.Context, arg UpsertRocketChatCredentialsParams) error
	UpsertRoom(ctx context.Context, arg UpsertRoomParams) (Room, error)
	UpsertSkill(ctx context.Context, arg UpsertSkillParams) (Skill, error)
	UpsertUserBotSettings(ctx context.Context, arg UpsertUserBotSettingsParams) (UserBotSetting, error)
}

var _ Querier = (*Queries)(nil)
