// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/student.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/student.go -destination=internal/service/mock/student_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	service "github.com/vgy789/noemx21-bot/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockStudentService is a mock of StudentService interface.
type MockStudentService struct {
	ctrl     *gomock.Controller
	recorder *MockStudentServiceMockRecorder
	isgomock struct{}
}

// MockStudentServiceMockRecorder is the mock recorder for MockStudentService.
type MockStudentServiceMockRecorder struct {
	mock *MockStudentService
}

// NewMockStudentService creates a new mock instance.
func NewMockStudentService(ctrl *gomock.Controller) *MockStudentService {
	mock := &MockStudentService{ctrl: ctrl}
	mock.recorder = &MockStudentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentService) EXPECT() *MockStudentServiceMockRecorder {
	return m.recorder
}

// GetProfileByTelegramID mocks base method.
func (m *MockStudentService) GetProfileByTelegramID(ctx context.Context, tgID int64) (*service.StudentProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByTelegramID", ctx, tgID)
	ret0, _ := ret[0].(*service.StudentProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByTelegramID indicates an expected call of GetProfileByTelegramID.
func (mr *MockStudentServiceMockRecorder) GetProfileByTelegramID(ctx, tgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByTelegramID", reflect.TypeOf((*MockStudentService)(nil).GetProfileByTelegramID), ctx, tgID)
}
