// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	db "github.com/vgy789/noemx21-bot/internal/database/db"
	service "github.com/vgy789/noemx21-bot/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// GetProfileByExternalID mocks base method.
func (m *MockUserService) GetProfileByExternalID(ctx context.Context, platform db.EnumPlatform, externalID string) (*service.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByExternalID", ctx, platform, externalID)
	ret0, _ := ret[0].(*service.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByExternalID indicates an expected call of GetProfileByExternalID.
func (mr *MockUserServiceMockRecorder) GetProfileByExternalID(ctx, platform, externalID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByExternalID", reflect.TypeOf((*MockUserService)(nil).GetProfileByExternalID), ctx, platform, externalID)
}

// GetProfileByTelegramID mocks base method.
func (m *MockUserService) GetProfileByTelegramID(ctx context.Context, tgID int64) (*service.UserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByTelegramID", ctx, tgID)
	ret0, _ := ret[0].(*service.UserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByTelegramID indicates an expected call of GetProfileByTelegramID.
func (mr *MockUserServiceMockRecorder) GetProfileByTelegramID(ctx, tgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByTelegramID", reflect.TypeOf((*MockUserService)(nil).GetProfileByTelegramID), ctx, tgID)
}
