// Code generated by MockGen. DO NOT EDIT.
// Source: internal/database/db/querier.go
//
// Generated by this command:
//
//	mockgen -source=internal/database/db/querier.go -destination=internal/database/db/mock/querier_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	db "github.com/vgy789/noemx21-bot/internal/database/db"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CreateApiKey mocks base method.
func (m *MockQuerier) CreateApiKey(ctx context.Context, arg db.CreateApiKeyParams) (db.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApiKey", ctx, arg)
	ret0, _ := ret[0].(db.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApiKey indicates an expected call of CreateApiKey.
func (mr *MockQuerierMockRecorder) CreateApiKey(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApiKey", reflect.TypeOf((*MockQuerier)(nil).CreateApiKey), ctx, arg)
}

// CreateAuthVerificationCode mocks base method.
func (m *MockQuerier) CreateAuthVerificationCode(ctx context.Context, arg db.CreateAuthVerificationCodeParams) (db.AuthVerificationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthVerificationCode", ctx, arg)
	ret0, _ := ret[0].(db.AuthVerificationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuthVerificationCode indicates an expected call of CreateAuthVerificationCode.
func (mr *MockQuerierMockRecorder) CreateAuthVerificationCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthVerificationCode", reflect.TypeOf((*MockQuerier)(nil).CreateAuthVerificationCode), ctx, arg)
}

// CreateUserAccount mocks base method.
func (m *MockQuerier) CreateUserAccount(ctx context.Context, arg db.CreateUserAccountParams) (db.UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserAccount", ctx, arg)
	ret0, _ := ret[0].(db.UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserAccount indicates an expected call of CreateUserAccount.
func (mr *MockQuerierMockRecorder) CreateUserAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserAccount", reflect.TypeOf((*MockQuerier)(nil).CreateUserAccount), ctx, arg)
}

// DeactivateClubsByCampus mocks base method.
func (m *MockQuerier) DeactivateClubsByCampus(ctx context.Context, campusID pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateClubsByCampus", ctx, campusID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateClubsByCampus indicates an expected call of DeactivateClubsByCampus.
func (mr *MockQuerierMockRecorder) DeactivateClubsByCampus(ctx, campusID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateClubsByCampus", reflect.TypeOf((*MockQuerier)(nil).DeactivateClubsByCampus), ctx, campusID)
}

// DeleteAllAuthVerificationCodes mocks base method.
func (m *MockQuerier) DeleteAllAuthVerificationCodes(ctx context.Context, s21Login pgtype.Text) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllAuthVerificationCodes", ctx, s21Login)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllAuthVerificationCodes indicates an expected call of DeleteAllAuthVerificationCodes.
func (mr *MockQuerierMockRecorder) DeleteAllAuthVerificationCodes(ctx, s21Login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllAuthVerificationCodes", reflect.TypeOf((*MockQuerier)(nil).DeleteAllAuthVerificationCodes), ctx, s21Login)
}

// DeleteAuthVerificationCode mocks base method.
func (m *MockQuerier) DeleteAuthVerificationCode(ctx context.Context, arg db.DeleteAuthVerificationCodeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAuthVerificationCode", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAuthVerificationCode indicates an expected call of DeleteAuthVerificationCode.
func (mr *MockQuerierMockRecorder) DeleteAuthVerificationCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAuthVerificationCode", reflect.TypeOf((*MockQuerier)(nil).DeleteAuthVerificationCode), ctx, arg)
}

// DeleteExpiredAuthVerificationCodes mocks base method.
func (m *MockQuerier) DeleteExpiredAuthVerificationCodes(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredAuthVerificationCodes", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredAuthVerificationCodes indicates an expected call of DeleteExpiredAuthVerificationCodes.
func (mr *MockQuerierMockRecorder) DeleteExpiredAuthVerificationCodes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredAuthVerificationCodes", reflect.TypeOf((*MockQuerier)(nil).DeleteExpiredAuthVerificationCodes), ctx)
}

// DeleteUserAccountByExternalId mocks base method.
func (m *MockQuerier) DeleteUserAccountByExternalId(ctx context.Context, arg db.DeleteUserAccountByExternalIdParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserAccountByExternalId", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserAccountByExternalId indicates an expected call of DeleteUserAccountByExternalId.
func (mr *MockQuerierMockRecorder) DeleteUserAccountByExternalId(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserAccountByExternalId", reflect.TypeOf((*MockQuerier)(nil).DeleteUserAccountByExternalId), ctx, arg)
}

// GetActiveApiKey mocks base method.
func (m *MockQuerier) GetActiveApiKey(ctx context.Context, userAccountID int64) (db.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveApiKey", ctx, userAccountID)
	ret0, _ := ret[0].(db.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveApiKey indicates an expected call of GetActiveApiKey.
func (mr *MockQuerierMockRecorder) GetActiveApiKey(ctx, userAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveApiKey", reflect.TypeOf((*MockQuerier)(nil).GetActiveApiKey), ctx, userAccountID)
}

// GetApiKeyByHash mocks base method.
func (m *MockQuerier) GetApiKeyByHash(ctx context.Context, keyHash string) (db.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiKeyByHash", ctx, keyHash)
	ret0, _ := ret[0].(db.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiKeyByHash indicates an expected call of GetApiKeyByHash.
func (mr *MockQuerierMockRecorder) GetApiKeyByHash(ctx, keyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiKeyByHash", reflect.TypeOf((*MockQuerier)(nil).GetApiKeyByHash), ctx, keyHash)
}

// GetCampusByID mocks base method.
func (m *MockQuerier) GetCampusByID(ctx context.Context, id pgtype.UUID) (db.GetCampusByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampusByID", ctx, id)
	ret0, _ := ret[0].(db.GetCampusByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampusByID indicates an expected call of GetCampusByID.
func (mr *MockQuerierMockRecorder) GetCampusByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampusByID", reflect.TypeOf((*MockQuerier)(nil).GetCampusByID), ctx, id)
}

// GetCampusByShortName mocks base method.
func (m *MockQuerier) GetCampusByShortName(ctx context.Context, shortName string) (db.Campuse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampusByShortName", ctx, shortName)
	ret0, _ := ret[0].(db.Campuse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampusByShortName indicates an expected call of GetCampusByShortName.
func (mr *MockQuerierMockRecorder) GetCampusByShortName(ctx, shortName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampusByShortName", reflect.TypeOf((*MockQuerier)(nil).GetCampusByShortName), ctx, shortName)
}

// GetFSMState mocks base method.
func (m *MockQuerier) GetFSMState(ctx context.Context, userID int64) (db.FsmUserState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFSMState", ctx, userID)
	ret0, _ := ret[0].(db.FsmUserState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFSMState indicates an expected call of GetFSMState.
func (mr *MockQuerierMockRecorder) GetFSMState(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFSMState", reflect.TypeOf((*MockQuerier)(nil).GetFSMState), ctx, userID)
}

// GetGlobalClubs mocks base method.
func (m *MockQuerier) GetGlobalClubs(ctx context.Context) ([]db.GetGlobalClubsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobalClubs", ctx)
	ret0, _ := ret[0].([]db.GetGlobalClubsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalClubs indicates an expected call of GetGlobalClubs.
func (mr *MockQuerierMockRecorder) GetGlobalClubs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalClubs", reflect.TypeOf((*MockQuerier)(nil).GetGlobalClubs), ctx)
}

// GetLastAuthVerificationCode mocks base method.
func (m *MockQuerier) GetLastAuthVerificationCode(ctx context.Context, s21Login pgtype.Text) (db.AuthVerificationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastAuthVerificationCode", ctx, s21Login)
	ret0, _ := ret[0].(db.AuthVerificationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastAuthVerificationCode indicates an expected call of GetLastAuthVerificationCode.
func (mr *MockQuerierMockRecorder) GetLastAuthVerificationCode(ctx, s21Login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastAuthVerificationCode", reflect.TypeOf((*MockQuerier)(nil).GetLastAuthVerificationCode), ctx, s21Login)
}

// GetLocalClubs mocks base method.
func (m *MockQuerier) GetLocalClubs(ctx context.Context, campusID pgtype.UUID) ([]db.GetLocalClubsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalClubs", ctx, campusID)
	ret0, _ := ret[0].([]db.GetLocalClubsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocalClubs indicates an expected call of GetLocalClubs.
func (mr *MockQuerierMockRecorder) GetLocalClubs(ctx, campusID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalClubs", reflect.TypeOf((*MockQuerier)(nil).GetLocalClubs), ctx, campusID)
}

// GetMyProfile mocks base method.
func (m *MockQuerier) GetMyProfile(ctx context.Context, s21Login string) (db.GetMyProfileRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyProfile", ctx, s21Login)
	ret0, _ := ret[0].(db.GetMyProfileRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyProfile indicates an expected call of GetMyProfile.
func (mr *MockQuerierMockRecorder) GetMyProfile(ctx, s21Login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyProfile", reflect.TypeOf((*MockQuerier)(nil).GetMyProfile), ctx, s21Login)
}

// GetParticipantSkills mocks base method.
func (m *MockQuerier) GetParticipantSkills(ctx context.Context, s21Login string) ([]db.GetParticipantSkillsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParticipantSkills", ctx, s21Login)
	ret0, _ := ret[0].([]db.GetParticipantSkillsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipantSkills indicates an expected call of GetParticipantSkills.
func (mr *MockQuerierMockRecorder) GetParticipantSkills(ctx, s21Login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipantSkills", reflect.TypeOf((*MockQuerier)(nil).GetParticipantSkills), ctx, s21Login)
}

// GetParticipantStatsCache mocks base method.
func (m *MockQuerier) GetParticipantStatsCache(ctx context.Context, s21Login string) (db.GetParticipantStatsCacheRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParticipantStatsCache", ctx, s21Login)
	ret0, _ := ret[0].(db.GetParticipantStatsCacheRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipantStatsCache indicates an expected call of GetParticipantStatsCache.
func (mr *MockQuerierMockRecorder) GetParticipantStatsCache(ctx, s21Login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipantStatsCache", reflect.TypeOf((*MockQuerier)(nil).GetParticipantStatsCache), ctx, s21Login)
}

// GetPeerProfile mocks base method.
func (m *MockQuerier) GetPeerProfile(ctx context.Context, s21Login string) (db.GetPeerProfileRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeerProfile", ctx, s21Login)
	ret0, _ := ret[0].(db.GetPeerProfileRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeerProfile indicates an expected call of GetPeerProfile.
func (mr *MockQuerierMockRecorder) GetPeerProfile(ctx, s21Login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeerProfile", reflect.TypeOf((*MockQuerier)(nil).GetPeerProfile), ctx, s21Login)
}

// GetPlatformCredentials mocks base method.
func (m *MockQuerier) GetPlatformCredentials(ctx context.Context, s21Login string) (db.PlatformCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlatformCredentials", ctx, s21Login)
	ret0, _ := ret[0].(db.PlatformCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlatformCredentials indicates an expected call of GetPlatformCredentials.
func (mr *MockQuerierMockRecorder) GetPlatformCredentials(ctx, s21Login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlatformCredentials", reflect.TypeOf((*MockQuerier)(nil).GetPlatformCredentials), ctx, s21Login)
}

// GetRegisteredUserByRocketChatId mocks base method.
func (m *MockQuerier) GetRegisteredUserByRocketChatId(ctx context.Context, rocketchatID string) (db.RegisteredUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegisteredUserByRocketChatId", ctx, rocketchatID)
	ret0, _ := ret[0].(db.RegisteredUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegisteredUserByRocketChatId indicates an expected call of GetRegisteredUserByRocketChatId.
func (mr *MockQuerierMockRecorder) GetRegisteredUserByRocketChatId(ctx, rocketchatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegisteredUserByRocketChatId", reflect.TypeOf((*MockQuerier)(nil).GetRegisteredUserByRocketChatId), ctx, rocketchatID)
}

// GetRegisteredUserByS21Login mocks base method.
func (m *MockQuerier) GetRegisteredUserByS21Login(ctx context.Context, s21Login string) (db.RegisteredUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegisteredUserByS21Login", ctx, s21Login)
	ret0, _ := ret[0].(db.RegisteredUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegisteredUserByS21Login indicates an expected call of GetRegisteredUserByS21Login.
func (mr *MockQuerierMockRecorder) GetRegisteredUserByS21Login(ctx, s21Login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegisteredUserByS21Login", reflect.TypeOf((*MockQuerier)(nil).GetRegisteredUserByS21Login), ctx, s21Login)
}

// GetRocketChatCredentials mocks base method.
func (m *MockQuerier) GetRocketChatCredentials(ctx context.Context, s21Login string) (db.RocketchatCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRocketChatCredentials", ctx, s21Login)
	ret0, _ := ret[0].(db.RocketchatCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRocketChatCredentials indicates an expected call of GetRocketChatCredentials.
func (mr *MockQuerierMockRecorder) GetRocketChatCredentials(ctx, s21Login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRocketChatCredentials", reflect.TypeOf((*MockQuerier)(nil).GetRocketChatCredentials), ctx, s21Login)
}

// GetUserAccountByExternalId mocks base method.
func (m *MockQuerier) GetUserAccountByExternalId(ctx context.Context, arg db.GetUserAccountByExternalIdParams) (db.UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccountByExternalId", ctx, arg)
	ret0, _ := ret[0].(db.UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccountByExternalId indicates an expected call of GetUserAccountByExternalId.
func (mr *MockQuerierMockRecorder) GetUserAccountByExternalId(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccountByExternalId", reflect.TypeOf((*MockQuerier)(nil).GetUserAccountByExternalId), ctx, arg)
}

// GetUserAccountByS21Login mocks base method.
func (m *MockQuerier) GetUserAccountByS21Login(ctx context.Context, s21Login string) (db.UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccountByS21Login", ctx, s21Login)
	ret0, _ := ret[0].(db.UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccountByS21Login indicates an expected call of GetUserAccountByS21Login.
func (mr *MockQuerierMockRecorder) GetUserAccountByS21Login(ctx, s21Login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccountByS21Login", reflect.TypeOf((*MockQuerier)(nil).GetUserAccountByS21Login), ctx, s21Login)
}

// GetUserBotSettings mocks base method.
func (m *MockQuerier) GetUserBotSettings(ctx context.Context, userAccountID int64) (db.UserBotSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBotSettings", ctx, userAccountID)
	ret0, _ := ret[0].(db.UserBotSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBotSettings indicates an expected call of GetUserBotSettings.
func (mr *MockQuerierMockRecorder) GetUserBotSettings(ctx, userAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBotSettings", reflect.TypeOf((*MockQuerier)(nil).GetUserBotSettings), ctx, userAccountID)
}

// GetValidAuthVerificationCode mocks base method.
func (m *MockQuerier) GetValidAuthVerificationCode(ctx context.Context, arg db.GetValidAuthVerificationCodeParams) (db.AuthVerificationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidAuthVerificationCode", ctx, arg)
	ret0, _ := ret[0].(db.AuthVerificationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidAuthVerificationCode indicates an expected call of GetValidAuthVerificationCode.
func (mr *MockQuerierMockRecorder) GetValidAuthVerificationCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidAuthVerificationCode", reflect.TypeOf((*MockQuerier)(nil).GetValidAuthVerificationCode), ctx, arg)
}

// RevokeOldApiKeys mocks base method.
func (m *MockQuerier) RevokeOldApiKeys(ctx context.Context, userAccountID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeOldApiKeys", ctx, userAccountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeOldApiKeys indicates an expected call of RevokeOldApiKeys.
func (mr *MockQuerierMockRecorder) RevokeOldApiKeys(ctx, userAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeOldApiKeys", reflect.TypeOf((*MockQuerier)(nil).RevokeOldApiKeys), ctx, userAccountID)
}

// UpsertCampus mocks base method.
func (m *MockQuerier) UpsertCampus(ctx context.Context, arg db.UpsertCampusParams) (db.Campuse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCampus", ctx, arg)
	ret0, _ := ret[0].(db.Campuse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCampus indicates an expected call of UpsertCampus.
func (mr *MockQuerierMockRecorder) UpsertCampus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCampus", reflect.TypeOf((*MockQuerier)(nil).UpsertCampus), ctx, arg)
}

// UpsertClub mocks base method.
func (m *MockQuerier) UpsertClub(ctx context.Context, arg db.UpsertClubParams) (db.Club, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertClub", ctx, arg)
	ret0, _ := ret[0].(db.Club)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertClub indicates an expected call of UpsertClub.
func (mr *MockQuerierMockRecorder) UpsertClub(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertClub", reflect.TypeOf((*MockQuerier)(nil).UpsertClub), ctx, arg)
}

// UpsertClubCategory mocks base method.
func (m *MockQuerier) UpsertClubCategory(ctx context.Context, name string) (db.ClubCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertClubCategory", ctx, name)
	ret0, _ := ret[0].(db.ClubCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertClubCategory indicates an expected call of UpsertClubCategory.
func (mr *MockQuerierMockRecorder) UpsertClubCategory(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertClubCategory", reflect.TypeOf((*MockQuerier)(nil).UpsertClubCategory), ctx, name)
}

// UpsertCoalition mocks base method.
func (m *MockQuerier) UpsertCoalition(ctx context.Context, arg db.UpsertCoalitionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCoalition", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCoalition indicates an expected call of UpsertCoalition.
func (mr *MockQuerierMockRecorder) UpsertCoalition(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCoalition", reflect.TypeOf((*MockQuerier)(nil).UpsertCoalition), ctx, arg)
}

// UpsertFSMState mocks base method.
func (m *MockQuerier) UpsertFSMState(ctx context.Context, arg db.UpsertFSMStateParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFSMState", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertFSMState indicates an expected call of UpsertFSMState.
func (mr *MockQuerierMockRecorder) UpsertFSMState(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFSMState", reflect.TypeOf((*MockQuerier)(nil).UpsertFSMState), ctx, arg)
}

// UpsertParticipantSkill mocks base method.
func (m *MockQuerier) UpsertParticipantSkill(ctx context.Context, arg db.UpsertParticipantSkillParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertParticipantSkill", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertParticipantSkill indicates an expected call of UpsertParticipantSkill.
func (mr *MockQuerierMockRecorder) UpsertParticipantSkill(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertParticipantSkill", reflect.TypeOf((*MockQuerier)(nil).UpsertParticipantSkill), ctx, arg)
}

// UpsertParticipantStatsCache mocks base method.
func (m *MockQuerier) UpsertParticipantStatsCache(ctx context.Context, arg db.UpsertParticipantStatsCacheParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertParticipantStatsCache", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertParticipantStatsCache indicates an expected call of UpsertParticipantStatsCache.
func (mr *MockQuerierMockRecorder) UpsertParticipantStatsCache(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertParticipantStatsCache", reflect.TypeOf((*MockQuerier)(nil).UpsertParticipantStatsCache), ctx, arg)
}

// UpsertPlatformCredentials mocks base method.
func (m *MockQuerier) UpsertPlatformCredentials(ctx context.Context, arg db.UpsertPlatformCredentialsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPlatformCredentials", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertPlatformCredentials indicates an expected call of UpsertPlatformCredentials.
func (mr *MockQuerierMockRecorder) UpsertPlatformCredentials(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPlatformCredentials", reflect.TypeOf((*MockQuerier)(nil).UpsertPlatformCredentials), ctx, arg)
}

// UpsertRegisteredUser mocks base method.
func (m *MockQuerier) UpsertRegisteredUser(ctx context.Context, arg db.UpsertRegisteredUserParams) (db.RegisteredUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRegisteredUser", ctx, arg)
	ret0, _ := ret[0].(db.RegisteredUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertRegisteredUser indicates an expected call of UpsertRegisteredUser.
func (mr *MockQuerierMockRecorder) UpsertRegisteredUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRegisteredUser", reflect.TypeOf((*MockQuerier)(nil).UpsertRegisteredUser), ctx, arg)
}

// UpsertRocketChatCredentials mocks base method.
func (m *MockQuerier) UpsertRocketChatCredentials(ctx context.Context, arg db.UpsertRocketChatCredentialsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRocketChatCredentials", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRocketChatCredentials indicates an expected call of UpsertRocketChatCredentials.
func (mr *MockQuerierMockRecorder) UpsertRocketChatCredentials(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRocketChatCredentials", reflect.TypeOf((*MockQuerier)(nil).UpsertRocketChatCredentials), ctx, arg)
}

// UpsertSkill mocks base method.
func (m *MockQuerier) UpsertSkill(ctx context.Context, arg db.UpsertSkillParams) (db.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSkill", ctx, arg)
	ret0, _ := ret[0].(db.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertSkill indicates an expected call of UpsertSkill.
func (mr *MockQuerierMockRecorder) UpsertSkill(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSkill", reflect.TypeOf((*MockQuerier)(nil).UpsertSkill), ctx, arg)
}

// UpsertUserBotSettings mocks base method.
func (m *MockQuerier) UpsertUserBotSettings(ctx context.Context, arg db.UpsertUserBotSettingsParams) (db.UserBotSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserBotSettings", ctx, arg)
	ret0, _ := ret[0].(db.UserBotSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUserBotSettings indicates an expected call of UpsertUserBotSettings.
func (mr *MockQuerierMockRecorder) UpsertUserBotSettings(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserBotSettings", reflect.TypeOf((*MockQuerier)(nil).UpsertUserBotSettings), ctx, arg)
}
