// Code generated by MockGen. DO NOT EDIT.
// Source: internal/database/db/querier.go
//
// Generated by this command:
//
//	mockgen -source=internal/database/db/querier.go -destination=internal/database/db/mock/querier_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	db "github.com/vgy789/noemx21-bot/internal/database/db"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CreateApiKey mocks base method.
func (m *MockQuerier) CreateApiKey(ctx context.Context, arg db.CreateApiKeyParams) (db.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApiKey", ctx, arg)
	ret0, _ := ret[0].(db.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApiKey indicates an expected call of CreateApiKey.
func (mr *MockQuerierMockRecorder) CreateApiKey(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApiKey", reflect.TypeOf((*MockQuerier)(nil).CreateApiKey), ctx, arg)
}

// CreateAuthVerificationCode mocks base method.
func (m *MockQuerier) CreateAuthVerificationCode(ctx context.Context, arg db.CreateAuthVerificationCodeParams) (db.AuthVerificationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthVerificationCode", ctx, arg)
	ret0, _ := ret[0].(db.AuthVerificationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuthVerificationCode indicates an expected call of CreateAuthVerificationCode.
func (mr *MockQuerierMockRecorder) CreateAuthVerificationCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthVerificationCode", reflect.TypeOf((*MockQuerier)(nil).CreateAuthVerificationCode), ctx, arg)
}

// CreateUserAccount mocks base method.
func (m *MockQuerier) CreateUserAccount(ctx context.Context, arg db.CreateUserAccountParams) (db.UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserAccount", ctx, arg)
	ret0, _ := ret[0].(db.UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserAccount indicates an expected call of CreateUserAccount.
func (mr *MockQuerierMockRecorder) CreateUserAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserAccount", reflect.TypeOf((*MockQuerier)(nil).CreateUserAccount), ctx, arg)
}

// DeactivateClubsByCampus mocks base method.
func (m *MockQuerier) DeactivateClubsByCampus(ctx context.Context, campusID pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateClubsByCampus", ctx, campusID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateClubsByCampus indicates an expected call of DeactivateClubsByCampus.
func (mr *MockQuerierMockRecorder) DeactivateClubsByCampus(ctx, campusID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateClubsByCampus", reflect.TypeOf((*MockQuerier)(nil).DeactivateClubsByCampus), ctx, campusID)
}

// DeleteAllAuthVerificationCodes mocks base method.
func (m *MockQuerier) DeleteAllAuthVerificationCodes(ctx context.Context, studentID pgtype.Text) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllAuthVerificationCodes", ctx, studentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllAuthVerificationCodes indicates an expected call of DeleteAllAuthVerificationCodes.
func (mr *MockQuerierMockRecorder) DeleteAllAuthVerificationCodes(ctx, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllAuthVerificationCodes", reflect.TypeOf((*MockQuerier)(nil).DeleteAllAuthVerificationCodes), ctx, studentID)
}

// DeleteAuthVerificationCode mocks base method.
func (m *MockQuerier) DeleteAuthVerificationCode(ctx context.Context, arg db.DeleteAuthVerificationCodeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAuthVerificationCode", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAuthVerificationCode indicates an expected call of DeleteAuthVerificationCode.
func (mr *MockQuerierMockRecorder) DeleteAuthVerificationCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAuthVerificationCode", reflect.TypeOf((*MockQuerier)(nil).DeleteAuthVerificationCode), ctx, arg)
}

// DeleteExpiredAuthVerificationCodes mocks base method.
func (m *MockQuerier) DeleteExpiredAuthVerificationCodes(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredAuthVerificationCodes", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredAuthVerificationCodes indicates an expected call of DeleteExpiredAuthVerificationCodes.
func (mr *MockQuerierMockRecorder) DeleteExpiredAuthVerificationCodes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredAuthVerificationCodes", reflect.TypeOf((*MockQuerier)(nil).DeleteExpiredAuthVerificationCodes), ctx)
}

// GetActiveApiKey mocks base method.
func (m *MockQuerier) GetActiveApiKey(ctx context.Context, userAccountID int64) (db.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveApiKey", ctx, userAccountID)
	ret0, _ := ret[0].(db.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveApiKey indicates an expected call of GetActiveApiKey.
func (mr *MockQuerierMockRecorder) GetActiveApiKey(ctx, userAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveApiKey", reflect.TypeOf((*MockQuerier)(nil).GetActiveApiKey), ctx, userAccountID)
}

// GetApiKeyByHash mocks base method.
func (m *MockQuerier) GetApiKeyByHash(ctx context.Context, keyHash string) (db.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiKeyByHash", ctx, keyHash)
	ret0, _ := ret[0].(db.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiKeyByHash indicates an expected call of GetApiKeyByHash.
func (mr *MockQuerierMockRecorder) GetApiKeyByHash(ctx, keyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiKeyByHash", reflect.TypeOf((*MockQuerier)(nil).GetApiKeyByHash), ctx, keyHash)
}

// GetCampusByShortName mocks base method.
func (m *MockQuerier) GetCampusByShortName(ctx context.Context, shortName string) (db.Campuse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampusByShortName", ctx, shortName)
	ret0, _ := ret[0].(db.Campuse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampusByShortName indicates an expected call of GetCampusByShortName.
func (mr *MockQuerierMockRecorder) GetCampusByShortName(ctx, shortName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampusByShortName", reflect.TypeOf((*MockQuerier)(nil).GetCampusByShortName), ctx, shortName)
}

// GetFSMState mocks base method.
func (m *MockQuerier) GetFSMState(ctx context.Context, userID int64) (db.FsmUserState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFSMState", ctx, userID)
	ret0, _ := ret[0].(db.FsmUserState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFSMState indicates an expected call of GetFSMState.
func (mr *MockQuerierMockRecorder) GetFSMState(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFSMState", reflect.TypeOf((*MockQuerier)(nil).GetFSMState), ctx, userID)
}

// GetLastAuthVerificationCode mocks base method.
func (m *MockQuerier) GetLastAuthVerificationCode(ctx context.Context, studentID pgtype.Text) (db.AuthVerificationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastAuthVerificationCode", ctx, studentID)
	ret0, _ := ret[0].(db.AuthVerificationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastAuthVerificationCode indicates an expected call of GetLastAuthVerificationCode.
func (mr *MockQuerierMockRecorder) GetLastAuthVerificationCode(ctx, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastAuthVerificationCode", reflect.TypeOf((*MockQuerier)(nil).GetLastAuthVerificationCode), ctx, studentID)
}

// GetPeerProfile mocks base method.
func (m *MockQuerier) GetPeerProfile(ctx context.Context, s21Login string) (db.GetPeerProfileRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeerProfile", ctx, s21Login)
	ret0, _ := ret[0].(db.GetPeerProfileRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeerProfile indicates an expected call of GetPeerProfile.
func (mr *MockQuerierMockRecorder) GetPeerProfile(ctx, s21Login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeerProfile", reflect.TypeOf((*MockQuerier)(nil).GetPeerProfile), ctx, s21Login)
}

// GetPlatformCredentials mocks base method.
func (m *MockQuerier) GetPlatformCredentials(ctx context.Context, studentID string) (db.PlatformCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlatformCredentials", ctx, studentID)
	ret0, _ := ret[0].(db.PlatformCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlatformCredentials indicates an expected call of GetPlatformCredentials.
func (mr *MockQuerierMockRecorder) GetPlatformCredentials(ctx, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlatformCredentials", reflect.TypeOf((*MockQuerier)(nil).GetPlatformCredentials), ctx, studentID)
}

// GetRocketChatCredentials mocks base method.
func (m *MockQuerier) GetRocketChatCredentials(ctx context.Context, studentID string) (db.RocketchatCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRocketChatCredentials", ctx, studentID)
	ret0, _ := ret[0].(db.RocketchatCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRocketChatCredentials indicates an expected call of GetRocketChatCredentials.
func (mr *MockQuerierMockRecorder) GetRocketChatCredentials(ctx, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRocketChatCredentials", reflect.TypeOf((*MockQuerier)(nil).GetRocketChatCredentials), ctx, studentID)
}

// GetStudentByRocketChatId mocks base method.
func (m *MockQuerier) GetStudentByRocketChatId(ctx context.Context, rocketchatID string) (db.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentByRocketChatId", ctx, rocketchatID)
	ret0, _ := ret[0].(db.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentByRocketChatId indicates an expected call of GetStudentByRocketChatId.
func (mr *MockQuerierMockRecorder) GetStudentByRocketChatId(ctx, rocketchatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentByRocketChatId", reflect.TypeOf((*MockQuerier)(nil).GetStudentByRocketChatId), ctx, rocketchatID)
}

// GetStudentByS21Login mocks base method.
func (m *MockQuerier) GetStudentByS21Login(ctx context.Context, s21Login string) (db.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentByS21Login", ctx, s21Login)
	ret0, _ := ret[0].(db.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentByS21Login indicates an expected call of GetStudentByS21Login.
func (mr *MockQuerierMockRecorder) GetStudentByS21Login(ctx, s21Login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentByS21Login", reflect.TypeOf((*MockQuerier)(nil).GetStudentByS21Login), ctx, s21Login)
}

// GetStudentProfile mocks base method.
func (m *MockQuerier) GetStudentProfile(ctx context.Context, s21Login string) (db.GetStudentProfileRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentProfile", ctx, s21Login)
	ret0, _ := ret[0].(db.GetStudentProfileRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentProfile indicates an expected call of GetStudentProfile.
func (mr *MockQuerierMockRecorder) GetStudentProfile(ctx, s21Login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentProfile", reflect.TypeOf((*MockQuerier)(nil).GetStudentProfile), ctx, s21Login)
}

// GetStudentSkills mocks base method.
func (m *MockQuerier) GetStudentSkills(ctx context.Context, studentID string) ([]db.GetStudentSkillsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentSkills", ctx, studentID)
	ret0, _ := ret[0].([]db.GetStudentSkillsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentSkills indicates an expected call of GetStudentSkills.
func (mr *MockQuerierMockRecorder) GetStudentSkills(ctx, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentSkills", reflect.TypeOf((*MockQuerier)(nil).GetStudentSkills), ctx, studentID)
}

// GetUserAccountByExternalId mocks base method.
func (m *MockQuerier) GetUserAccountByExternalId(ctx context.Context, arg db.GetUserAccountByExternalIdParams) (db.UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccountByExternalId", ctx, arg)
	ret0, _ := ret[0].(db.UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccountByExternalId indicates an expected call of GetUserAccountByExternalId.
func (mr *MockQuerierMockRecorder) GetUserAccountByExternalId(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccountByExternalId", reflect.TypeOf((*MockQuerier)(nil).GetUserAccountByExternalId), ctx, arg)
}

// GetUserAccountByStudentId mocks base method.
func (m *MockQuerier) GetUserAccountByStudentId(ctx context.Context, studentID string) (db.UserAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccountByStudentId", ctx, studentID)
	ret0, _ := ret[0].(db.UserAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccountByStudentId indicates an expected call of GetUserAccountByStudentId.
func (mr *MockQuerierMockRecorder) GetUserAccountByStudentId(ctx, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccountByStudentId", reflect.TypeOf((*MockQuerier)(nil).GetUserAccountByStudentId), ctx, studentID)
}

// GetUserBotSettings mocks base method.
func (m *MockQuerier) GetUserBotSettings(ctx context.Context, userAccountID int64) (db.UserBotSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBotSettings", ctx, userAccountID)
	ret0, _ := ret[0].(db.UserBotSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBotSettings indicates an expected call of GetUserBotSettings.
func (mr *MockQuerierMockRecorder) GetUserBotSettings(ctx, userAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBotSettings", reflect.TypeOf((*MockQuerier)(nil).GetUserBotSettings), ctx, userAccountID)
}

// GetValidAuthVerificationCode mocks base method.
func (m *MockQuerier) GetValidAuthVerificationCode(ctx context.Context, arg db.GetValidAuthVerificationCodeParams) (db.AuthVerificationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidAuthVerificationCode", ctx, arg)
	ret0, _ := ret[0].(db.AuthVerificationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidAuthVerificationCode indicates an expected call of GetValidAuthVerificationCode.
func (mr *MockQuerierMockRecorder) GetValidAuthVerificationCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidAuthVerificationCode", reflect.TypeOf((*MockQuerier)(nil).GetValidAuthVerificationCode), ctx, arg)
}

// RevokeOldApiKeys mocks base method.
func (m *MockQuerier) RevokeOldApiKeys(ctx context.Context, userAccountID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeOldApiKeys", ctx, userAccountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeOldApiKeys indicates an expected call of RevokeOldApiKeys.
func (mr *MockQuerierMockRecorder) RevokeOldApiKeys(ctx, userAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeOldApiKeys", reflect.TypeOf((*MockQuerier)(nil).RevokeOldApiKeys), ctx, userAccountID)
}

// UpdateStudentStats mocks base method.
func (m *MockQuerier) UpdateStudentStats(ctx context.Context, arg db.UpdateStudentStatsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStudentStats", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStudentStats indicates an expected call of UpdateStudentStats.
func (mr *MockQuerierMockRecorder) UpdateStudentStats(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStudentStats", reflect.TypeOf((*MockQuerier)(nil).UpdateStudentStats), ctx, arg)
}

// UpsertCampus mocks base method.
func (m *MockQuerier) UpsertCampus(ctx context.Context, arg db.UpsertCampusParams) (db.Campuse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCampus", ctx, arg)
	ret0, _ := ret[0].(db.Campuse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCampus indicates an expected call of UpsertCampus.
func (mr *MockQuerierMockRecorder) UpsertCampus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCampus", reflect.TypeOf((*MockQuerier)(nil).UpsertCampus), ctx, arg)
}

// UpsertClub mocks base method.
func (m *MockQuerier) UpsertClub(ctx context.Context, arg db.UpsertClubParams) (db.Club, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertClub", ctx, arg)
	ret0, _ := ret[0].(db.Club)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertClub indicates an expected call of UpsertClub.
func (mr *MockQuerierMockRecorder) UpsertClub(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertClub", reflect.TypeOf((*MockQuerier)(nil).UpsertClub), ctx, arg)
}

// UpsertClubCategory mocks base method.
func (m *MockQuerier) UpsertClubCategory(ctx context.Context, name string) (db.ClubCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertClubCategory", ctx, name)
	ret0, _ := ret[0].(db.ClubCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertClubCategory indicates an expected call of UpsertClubCategory.
func (mr *MockQuerierMockRecorder) UpsertClubCategory(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertClubCategory", reflect.TypeOf((*MockQuerier)(nil).UpsertClubCategory), ctx, name)
}

// UpsertCoalition mocks base method.
func (m *MockQuerier) UpsertCoalition(ctx context.Context, arg db.UpsertCoalitionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCoalition", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCoalition indicates an expected call of UpsertCoalition.
func (mr *MockQuerierMockRecorder) UpsertCoalition(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCoalition", reflect.TypeOf((*MockQuerier)(nil).UpsertCoalition), ctx, arg)
}

// UpsertFSMState mocks base method.
func (m *MockQuerier) UpsertFSMState(ctx context.Context, arg db.UpsertFSMStateParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFSMState", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertFSMState indicates an expected call of UpsertFSMState.
func (mr *MockQuerierMockRecorder) UpsertFSMState(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFSMState", reflect.TypeOf((*MockQuerier)(nil).UpsertFSMState), ctx, arg)
}

// UpsertPlatformCredentials mocks base method.
func (m *MockQuerier) UpsertPlatformCredentials(ctx context.Context, arg db.UpsertPlatformCredentialsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPlatformCredentials", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertPlatformCredentials indicates an expected call of UpsertPlatformCredentials.
func (mr *MockQuerierMockRecorder) UpsertPlatformCredentials(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPlatformCredentials", reflect.TypeOf((*MockQuerier)(nil).UpsertPlatformCredentials), ctx, arg)
}

// UpsertRocketChatCredentials mocks base method.
func (m *MockQuerier) UpsertRocketChatCredentials(ctx context.Context, arg db.UpsertRocketChatCredentialsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRocketChatCredentials", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRocketChatCredentials indicates an expected call of UpsertRocketChatCredentials.
func (mr *MockQuerierMockRecorder) UpsertRocketChatCredentials(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRocketChatCredentials", reflect.TypeOf((*MockQuerier)(nil).UpsertRocketChatCredentials), ctx, arg)
}

// UpsertSkill mocks base method.
func (m *MockQuerier) UpsertSkill(ctx context.Context, arg db.UpsertSkillParams) (db.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSkill", ctx, arg)
	ret0, _ := ret[0].(db.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertSkill indicates an expected call of UpsertSkill.
func (mr *MockQuerierMockRecorder) UpsertSkill(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSkill", reflect.TypeOf((*MockQuerier)(nil).UpsertSkill), ctx, arg)
}

// UpsertStudent mocks base method.
func (m *MockQuerier) UpsertStudent(ctx context.Context, arg db.UpsertStudentParams) (db.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertStudent", ctx, arg)
	ret0, _ := ret[0].(db.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertStudent indicates an expected call of UpsertStudent.
func (mr *MockQuerierMockRecorder) UpsertStudent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertStudent", reflect.TypeOf((*MockQuerier)(nil).UpsertStudent), ctx, arg)
}

// UpsertStudentSkill mocks base method.
func (m *MockQuerier) UpsertStudentSkill(ctx context.Context, arg db.UpsertStudentSkillParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertStudentSkill", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertStudentSkill indicates an expected call of UpsertStudentSkill.
func (mr *MockQuerierMockRecorder) UpsertStudentSkill(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertStudentSkill", reflect.TypeOf((*MockQuerier)(nil).UpsertStudentSkill), ctx, arg)
}

// UpsertUserBotSettings mocks base method.
func (m *MockQuerier) UpsertUserBotSettings(ctx context.Context, arg db.UpsertUserBotSettingsParams) (db.UserBotSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserBotSettings", ctx, arg)
	ret0, _ := ret[0].(db.UserBotSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUserBotSettings indicates an expected call of UpsertUserBotSettings.
func (mr *MockQuerierMockRecorder) UpsertUserBotSettings(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserBotSettings", reflect.TypeOf((*MockQuerier)(nil).UpsertUserBotSettings), ctx, arg)
}
