---
meta:
  feature_id: SET-001
  name: Настройки пользователя
  description: Управление настройками профиля, API-токенами и данными Data-Provider
  version: 2.0.2

initial_state: SETTINGS_MENU
states:
  SETTINGS_MENU:
    type: interactive
    description: Меню настроек
    interface:
      text:
        ru: |
          ⚙️ *Настройки*

          🆔 *Профиль*
          Укажи контакты (email, телефон) и настрой разрешения на входящие сообщения от пиров.

          🔑 *API*
          Подключи интеграцию с кампусом. Получи токен для аутентификации пиров в *своём* боте.
        en: |
          ⚙️ *Settings*

          🆔 *Profile*
          Set your contacts (email, phone) and configure incoming message permissions for peers.

          🔑 *API*
          Connect your campus to your bot. Get a token for authentication of peers in *your* bot.
      buttons:
        - id: profile
          label:
            ru: 🆔 Профиль
            en: 🆔 Profile
          next_state: PROFILE_SETTINGS
          row: 1
        - id: api
          label:
            ru: |
              🔑 API
            en: |
              🔑 API
          next_state: API_SETTINGS
          row: 1
        - id: language
          label:
            ru: "{my_lang_emoji} Язык бота"
            en: "{my_lang_emoji} Bot language"
          next_state: SET_LANGUAGE
        - id: back
          label:
            ru: 🏠 Назад
            en: 🏠 Back
          next_state: MAIN_MENU

  PROFILE_SETTINGS:
    type: interactive
    description: Настройки профиля
    interface:
      text:
        ru: |
          🆔 *Профиль*
        en: |
          🆔 *Profile*
      buttons:
        - id: searchable
          label:
            ru: "Видимость Telegram-профиля: {is_searchable_label_ru}"
            en: "Profile visibility: {is_searchable_label_en}"
          next_state: TOGGLE_SEARCHABLE
        - id: contact
          label:
            ru: Альтернативный способ связи
            en: Alternative Contact
          next_state: SET_ALTERNATIVE_CONTACT
        - id: back
          label:
            ru: ⬅️ Назад
            en: ⬅️ Back
          next_state: SETTINGS_MENU

  API_SETTINGS:
    type: interactive
    description: Настройки API
    interface:
      text:
        ru: |
          🔑 *API*

        en: |
          🔑 *API*
      buttons:
        - id: provider
          label:
            ru: Data-Provider
            en: Data-Provider
          next_state: CHECK_PROVIDER_CREDENTIALS
        - id: api_token
          label:
            ru: API-токен
            en: API Token
          next_state: MANAGE_API_TOKEN
        - id: back
          label:
            ru: 🔙 Назад
            en: 🔙 Back
          next_state: SETTINGS_MENU

  SET_ALTERNATIVE_CONTACT:
    type: input
    description: Альтернативный способ связи
    interface:
      text:
        ru: |
          Введи дополнительный способ связи (например, email или Telegram), либо удали текущий способ связи.
        en: |
          Enter additional contact (e.g., email or Telegram), or delete the current contact.
      error_invalid:
        ru: |
          ⚠️ Слишком длинный текст! Максимум 42 символов.
        en: |
          ⚠️ Text too long! Max 42 characters.
    validation:
      regex: ^.{1,42}$
    transitions:
      - trigger: on_valid_input
        next_state: CONFIRM_ALTERNATIVE_CONTACT
      - button: delete
        next_state: DELETE_ALTERNATIVE_CONTACT
      - button: back
        next_state: PROFILE_SETTINGS

  DELETE_ALTERNATIVE_CONTACT:
    type: system
    description: Удаление альтернативного способа связи
    logic:
      action: delete_alternative_contact
      payload:
        user_id: $context.user_id
    transitions:
      - next_state: PROFILE_SETTINGS

  CONFIRM_ALTERNATIVE_CONTACT:
    type: interactive
    description: Подтверждение альтернативного способа связи
    interface:
      text:
        ru: |
          ✅ Дополнительный контакт сохранен: {my_alt_contact}
        en: |
          ✅ Additional contact saved: {my_alt_contact}
      buttons:
        - id: back
          label:
            ru: 💾 Готово / Назад
            en: 💾 Done / Back
          next_state: PROFILE_SETTINGS

  ## интерфейс settings.yaml/SET_LANGUAGE и registration.yaml/SELECT_LANGUAGE должны совпадать
  SET_LANGUAGE:
    type: interactive
    description: Выбор языка бота
    interface:
      text:
        ru: 🌐 Выбери язык `/` Choose language
        en: 🌐 Выбери язык `/` Choose language
      buttons:
        - id: ru
          label:
            ru: 🇷🇺 Русский
            en: 🇷🇺 Russian
          next_state: SETTINGS_MENU
        - id: en
          label:
            ru: 🇺🇸 English
            en: 🇺🇸 English
          next_state: SETTINGS_MENU

  MANAGE_API_TOKEN:
    type: interactive
    description: Управление API-токеном
    interface:
      text:
        ru: |
          🔑 *Ты разработал бота и тебе нужно проверка является ли Telegram пользователь учеником Школы 21?* Получи API токен и отсылай реквесты через системные действия. Подробнее в документации.

          *API-токен*
          Твой текущий токен: {my_botapi_token}

          Нажми "Сгенерировать новый" для обновления.
        en: |
          🔑 *You developed a bot and need to check if the user is a current student of School 21? Get an API token and send requests via system actions. See documentation for details.*

          *API Token*
          Your current token: {my_botapi_token}

          Click "Generate new" to update.
      buttons:
        - id: regenerate
          label:
            ru: Сгенерировать новый
            en: Generate new
          next_state: GENERATE_API_TOKEN
        - id: back
          label:
            ru: 🔙 Назад
            en: 🔙 Back
          next_state: API_SETTINGS

  GENERATE_API_TOKEN:
    type: system
    description: Генерация нового API-токена
    logic:
      action: generate_api_token
      payload:
        user_id: $context.user_id
    transitions:
      - next_state: SHOW_NEW_API_TOKEN

  SHOW_NEW_API_TOKEN:
    type: interactive
    description: Отображение нового API-токена
    interface:
      text:
        ru: |
          ✅ Новый API-токен сгенерирован:

          `{my_botapi_token}`
        en: |
          ✅ New API token generated:

          `{my_botapi_token}`
      buttons:
        - id: back
          label:
            ru: 🔙 Назад
            en: 🔙 Back
          next_state: MANAGE_API_TOKEN

  CHECK_PROVIDER_CREDENTIALS:
    type: system
    description: Проверка наличия Data-Provider
    logic:
      action: is_provider_credentials
      payload:
        user_id: $context.user_id
    transitions:
      - condition: provider_credentials != null
        next_state: ALREADY_PROVIDER_CREDENTIALS
      - condition: provider_credentials == null
        next_state: NEED_PROVIDER_CREDENTIALS

  ALREADY_PROVIDER_CREDENTIALS:
    type: interactive
    description: Пользователь уже стал провайдером
    interface:
      text:
        ru: |
          Ты действующий провайдер! Спасибо! 🌟
        en: |
          You are an active provider! Thank you! 🌟
      buttons:
        - id: refuse
          label:
            ru: Отказаться от провайдерства
            en: Refuse to be a provider
          next_state: RESET_PROVIDER_CREDENTIALS
        - id: back
          label:
            ru: 🔙 Назад
            en: 🔙 Back
          next_state: API_SETTINGS

  RESET_PROVIDER_CREDENTIALS:
    type: system
    description: Сброс данных Data-Provider
    interface:
      text:
        ru: |
          ✅ Ты больше не провайдер!
        en: |
          ✅ You are no longer a provider!
    logic:
      action: reset_provider_credentials
      payload:
        user_id: $context.user_id
    transitions:
      - next_state: API_SETTINGS

  NEED_PROVIDER_CREDENTIALS:
    type: interactive
    description: Необходимость ввода данных Data-Provider
    interface:
      text:
        ru: |
          ℹ️ *Помоги боту получать данные из твоего кампуса – стань провайдером 😎.*
          Провайдеров в {my_campus} сейчас *{count}*.
        en: |
          ℹ️ *Help the bot get data from your campus – become a provider 😎.*
          There are currently *{count}* providers in {my_campus}.
      buttons:
        - id: set_provider_credentials
          label:
            ru: Стать провайдером
            en: Become a provider
          next_state: SET_PROVIDER_CREDENTIALS
        - id: back
          label:
            ru: 🔙 Назад
            en: 🔙 Back
          next_state: API_SETTINGS

  SET_PROVIDER_CREDENTIALS:
    type: input
    description: Ввод данных Data-Provider
    interface:
      text:
        ru: |
          Введи данные Data-Provider (логин, пароль, токен):
          (можно ввести все или часть)
        en: |
          Enter Data-Provider credentials (login, password, token):
          (can enter all or part)
      error_invalid:
        ru: |
          ⚠️ Я не нашёл токен или логин. Попробуй снова.
        en: |
          ⚠️ I didn't find a token or login. Try again.
    validation:
      regex: (?:ey[A-Za-z0-9\-_]+\.[A-Za-z0-9\-_]+\.[A-Za-z0-9\-_]+)|(?<![A-Za-z0-9\-_])[a-z]{4,9}(?![A-Za-z0-9\-_])
    transitions:
      - trigger: on_valid_input
        next_state: CONFIRM_PROVIDER_CREDENTIALS
      - trigger: on_invalid_input
        next_state: FAULT_PROVIDER_CREDENTIALS

  FAULT_PROVIDER_CREDENTIALS:
    type: interactive
    description: Неверные данные Data-Provider
    interface:
      text:
        ru: |
          ❌ Не удалось обратиться к API Школы с твоими данными. Перепроверь и попробуй снова.
        en: |
          ❌ Failed to connect to School API with your credentials. Check and try again.
      buttons:
        - id: back
          next_state: SET_PROVIDER_CREDENTIALS

  CONFIRM_PROVIDER_CREDENTIALS:
    type: interactive
    description: Подтверждение данных Data-Provider
    interface:
      text:
        ru: |
          ✅ Спасибо! Теперь бот будет получать данные из твоего кампуса.
        en: |
          ✅ Thanks! Now the bot will receive data from your campus.
      buttons:
        - id: back
          next_state: API_SETTINGS

  TOGGLE_SEARCHABLE:
    type: system
    description: Переключение видимости профиля
    logic:
      action: toggle_searchable
      payload:
        user_id: $context.user_id
    transitions:
      - next_state: SEARCHABLE_STATUS_NOTIFICATION

  SEARCHABLE_STATUS_NOTIFICATION:
    type: interactive
    description: Уведомление об изменении видимости
    interface:
      text:
        ru: |
          {status_emoji} Видимость профиля: {is_searchable_label_ru}.
          {search_restriction_ru}
        en: |
          {status_emoji} Profile visibility: {is_searchable_label_en}.
          {search_restriction_en}
      buttons:
        - id: back
          next_state: PROFILE_SETTINGS
