// Code generated by MockGen. DO NOT EDIT.
// Source: internal/transport/telegram/handlers.go
//
// Generated by this command:
//
//	mockgen -source=internal/transport/telegram/handlers.go -destination=internal/transport/telegram/mock/handlers_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gotgbot "github.com/PaulSonOfLars/gotgbot/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
	isgomock struct{}
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// AnswerCallbackQuery mocks base method.
func (m *MockSender) AnswerCallbackQuery(callbackQueryId string, opts *gotgbot.AnswerCallbackQueryOpts) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallbackQuery", callbackQueryId, opts)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnswerCallbackQuery indicates an expected call of AnswerCallbackQuery.
func (mr *MockSenderMockRecorder) AnswerCallbackQuery(callbackQueryId, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallbackQuery", reflect.TypeOf((*MockSender)(nil).AnswerCallbackQuery), callbackQueryId, opts)
}

// EditMessageText mocks base method.
func (m *MockSender) EditMessageText(text string, opts *gotgbot.EditMessageTextOpts) (*gotgbot.Message, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMessageText", text, opts)
	ret0, _ := ret[0].(*gotgbot.Message)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// EditMessageText indicates an expected call of EditMessageText.
func (mr *MockSenderMockRecorder) EditMessageText(text, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessageText", reflect.TypeOf((*MockSender)(nil).EditMessageText), text, opts)
}

// SendMessage mocks base method.
func (m *MockSender) SendMessage(chatID int64, text string, opts *gotgbot.SendMessageOpts) (*gotgbot.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", chatID, text, opts)
	ret0, _ := ret[0].(*gotgbot.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockSenderMockRecorder) SendMessage(chatID, text, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockSender)(nil).SendMessage), chatID, text, opts)
}
