// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Generated by this command:
//
//	mockgen -source=runner.go -destination=mock/runner_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTelegramService is a mock of TelegramService interface.
type MockTelegramService struct {
	ctrl     *gomock.Controller
	recorder *MockTelegramServiceMockRecorder
	isgomock struct{}
}

// MockTelegramServiceMockRecorder is the mock recorder for MockTelegramService.
type MockTelegramServiceMockRecorder struct {
	mock *MockTelegramService
}

// NewMockTelegramService creates a new mock instance.
func NewMockTelegramService(ctrl *gomock.Controller) *MockTelegramService {
	mock := &MockTelegramService{ctrl: ctrl}
	mock.recorder = &MockTelegramServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelegramService) EXPECT() *MockTelegramServiceMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockTelegramService) Run() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run")
}

// Run indicates an expected call of Run.
func (mr *MockTelegramServiceMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockTelegramService)(nil).Run))
}
